config-version: 2
name: 'sap'
version: '0.6.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
profile: 'dbt_production'

models:
  sap:
    +materialized: table
    +schema: sap
    staging:
      +materialized: view
    extractor_reports:
      intermediate:
        +materialized: table
    sales_and_procurement:
      star_schema:
        intermediate:
          +materialized: ephemeral
    compatibility_views:
      +schema: sap_comp_views
      +materialized: view
      intermediate:
        +materialized: ephemeral
        int_cosp__acdoca_derived:
          +materialized: view

vars:
  sap:
    acdoca: "{{ source('sap', 'acdoca') }}"
    bkpf: "{{ source('sap', 'bkpf') }}"
    bsad_bck: "{{ source('sap', 'bsad_bck') }}"
    bseg: "{{ source('sap', 'bseg') }}"
    coep: "{{ source('sap', 'coep') }}"
    dd07l: "{{ source('sap', 'dd07l') }}"
    dd07t: "{{ source('sap', 'dd07t') }}"
    ekko: "{{ source('sap', 'ekko') }}"
    ekbe: "{{ source('sap', 'ekbe') }}"
    eket: "{{ source('sap', 'eket') }}"
    ekpo: "{{ source('sap', 'ekpo') }}"
    faglflexa: "{{ source('sap', 'faglflexa') }}"
    faglflext: "{{ source('sap', 'faglflext') }}"
    finsc_cmp_versnd: "{{ source('sap', 'finsc_cmp_versnd') }}"
    finsc_ledger_rep: "{{ source('sap', 'finsc_ledger_rep') }}"
    finsc_ld_cmp: "{{ source('sap', 'finsc_ld_cmp') }}"
    kna1: "{{ source('sap', 'kna1') }}"
    lfa1: "{{ source('sap', 'lfa1') }}"
    makt: "{{ source('sap', 'makt') }}"
    mara: "{{ source('sap', 'mara') }}"
    marc: "{{ source('sap', 'marc') }}"
    matdoc: "{{ source('sap', 'matdoc') }}"
    matdoc_extract: "{{ source('sap', 'matdoc_extract') }}"
    mchb: "{{ source('sap', 'mchb') }}"
    mchp: "{{ source('sap', 'mchp') }}"
    pa0000: "{{ source('sap', 'pa0000') }}"
    pa0001: "{{ source('sap', 'pa0001') }}"
    pa0007: "{{ source('sap', 'pa0007') }}"
    pa0008: "{{ source('sap', 'pa0008') }}"
    pa0031: "{{ source('sap', 'pa0031') }}"
    prps: "{{ source('sap', 'prps') }}"
    ska1: "{{ source('sap', 'ska1') }}"
    t000: "{{ source('sap', 't000') }}"
    t001: "{{ source('sap', 't001') }}"
    t001w: "{{ source('sap', 't001w') }}"
    t024: "{{ source('sap', 't024') }}"
    t024e: "{{ source('sap', 't024e') }}"
    t134: "{{ source('sap', 't134') }}"
    t134t: "{{ source('sap', 't134t') }}"
    t161: "{{ source('sap', 't161') }}"
    t161t: "{{ source('sap', 't161t') }}"
    t503: "{{ source('sap', 't503') }}"
    t880: "{{ source('sap', 't880') }}"
    tj01: "{{ source('sap', 'tj01') }}"
    tka01: "{{ source('sap', 'tka01') }}"
    t006: "{{ source('sap', 't006') }}"
    cosp_bak: "{{ source('sap', 'cosp_bak') }}"
    tvag: "{{ source('sap', 'tvag') }}"
    tvagt: "{{ source('sap', 'tvagt') }}"
    vbak: "{{ source('sap', 'vbak') }}"
    vbap: "{{ source('sap', 'vbap') }}"
    vbuk: "{{ source('sap', 'vbuk') }}"
    vbup: "{{ source('sap', 'vbup') }}"
    sapsll_clsnr: "{{ source('sap', 'sapsll_clsnr') }}"
    sapsll_maritc: "{{ source('sap', 'sapsll_maritc') }}"
    sapsll_nosca: "{{ source('sap', 'sapsll_nosca') }}"
    sapsll_tunos: "{{ source('sap', 'sapsll_tunos') }}"
