config-version: 2
name: 'sap'
version: '0.1.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  sap:
    +materialized: table
    +schema: sap 

vars:
  sap:
    ## Staging Models
    bkpf: "{{ ref('stg_sap__bkpf') }}"
    bseg: "{{ ref('stg_sap__bseg') }}"
    faglflexa: "{{ ref('stg_sap__faglflexa') }}"
    faglflext: "{{ ref('stg_sap__faglflext') }}"
    kna1: "{{ ref('stg_sap__kna1') }}"
    lfa1: "{{ ref('stg_sap__lfa1') }}"
    mara: "{{ ref('stg_sap__mara') }}"
    pa0000: "{{ ref('stg_sap__pa0000') }}"
    pa0001: "{{ ref('stg_sap__pa0001') }}"
    pa0007: "{{ ref('stg_sap__pa0007') }}"
    pa0008: "{{ ref('stg_sap__pa0008') }}"
    pa0031: "{{ ref('stg_sap__pa0031') }}"
    ska1: "{{ ref('stg_sap__ska1') }}"
    t001: "{{ ref('stg_sap__t001') }}"
    t503: "{{ ref('stg_sap__t503') }}"
    t880: "{{ ref('stg_sap__t880') }}"