config-version: 2
name: 'sap'
version: '0.2.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  sap:
    +materialized: table
    +schema: sap 

vars:
  sap:
    bkpf: "{{ source('sap', 'bkpf') }}"
    bseg: "{{ source('sap', 'bseg') }}"
    dd07l: "{{ source('sap', 'dd07l') }}"
    dd07t: "{{ source('sap', 'dd07t') }}"
    ekko: "{{ source('sap', 'ekko') }}"
    ekbe: "{{ source('sap', 'ekbe') }}"
    eket: "{{ source('sap', 'eket') }}"
    ekpo: "{{ source('sap', 'ekpo') }}"
    faglflexa: "{{ source('sap', 'faglflexa') }}"
    faglflext: "{{ source('sap', 'faglflext') }}"
    kna1: "{{ source('sap', 'kna1') }}"
    lfa1: "{{ source('sap', 'lfa1') }}"
    makt: "{{ source('sap', 'makt') }}"
    mara: "{{ source('sap', 'mara') }}"
    pa0000: "{{ source('sap', 'pa0000') }}"
    pa0001: "{{ source('sap', 'pa0001') }}"
    pa0007: "{{ source('sap', 'pa0007') }}"
    pa0008: "{{ source('sap', 'pa0008') }}"
    pa0031: "{{ source('sap', 'pa0031') }}" 
    ska1: "{{ source('sap', 'ska1') }}"
    t001: "{{ source('sap', 't001') }}"
    t001w: "{{ source('sap', 't001w') }}"
    t024: "{{ source('sap', 't024') }}"
    t024e: "{{ source('sap', 't024e') }}"
    t134: "{{ source('sap', 't134') }}"
    t134t: "{{ source('sap', 't134t') }}"
    t161: "{{ source('sap', 't161') }}"
    t161t: "{{ source('sap', 't161t') }}"
    t503: "{{ source('sap', 't503') }}"
    t880: "{{ source('sap', 't880') }}"
    tvag: "{{ source('sap', 'tvag') }}"
    tvagt: "{{ source('sap', 'tvagt') }}"
    vbak: "{{ source('sap', 'vbak') }}"
    vbap: "{{ source('sap', 'vbap') }}"
    vbuk: "{{ source('sap', 'vbuk') }}"
    vbup: "{{ source('sap', 'vbup') }}"
