{{ config(enabled=var('sap_using_vbak', True)) }}

with base as (
    select *
    from {{ ref('stg_sap__vbak_tmp') }}
),

fields as (
    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=adapter.get_columns_in_relation(ref('stg_sap__vbak_tmp')),
                staging_columns=get_vbak_columns()
            )
        }}
    from base
),

final as (
    select
        _fivetran_deleted,
        _fivetran_synced,
        _fivetran_sap_archived,
        cast(mandt as {{ dbt.type_string() }}) as mandt,
        cast(vbeln as {{ dbt.type_string() }}) as vbeln,
        kostl,
        mahza,
        msr_id,
        _dataaging,
        taxk5,
        kvgr4,
        amtbl,
        trvog,
        hb_resdate,
        fmbdat,
        fsh_vrsn_status,
        upd_tmstmp,
        auart,
        hb_expdate,
        scheme_grp,
        smenr,
        taxk6,
        fsh_transaction,
        kvgr5,
        gskst,
        vkgrp,
        pay_method,
        ktext,
        ps_psp_pnr,
        faksk,
        bnddt,
        cmwae,
        kokrs,
        cast(kunnr as {{ dbt.type_string() }}) as kunnr,
        betc,
        fsh_rereg,
        tas,
        cancel_allow,
        fkara,
        taxk7,
        gwldt,
        psm_budat,
        objnr,
        autlf,
        stwae,
        abhov,
        logsysb,
        fsh_kvgr6,
        bname,
        taxk8,
        xblnr,
        mtlaur,
        augru,
        stafo,
        swenr,
        _xlso_trans_ctxt,
        abruf_part,
        cmngv,
        knkli,
        spart,
        proli,
        enqueue_grp,
        vzeit,
        kalcd,
        bukrs_vf,
        fsh_kvgr7,
        vprgr,
        crm_guid,
        hityp_pr,
        taxk9,
        vgbel,
        erzet,
        ihrez,
        submi,
        vdatu,
        _xlso_variant_id,
        abdis,
        fsh_kvgr8,
        ernam,
        hb_cont_reason,
        cast(netwr as {{ dbt.type_numeric() }}) as netwr,
        vbkla,
        vgtyp,
        sbgrp,
        stceg_l,
        fsh_kvgr10,
        knuma,
        fsh_ss,
        fsh_cq_check,
        xegdr,
        bstnk,
        multi,
        sppaym,
        lifsk,
        fsh_kvgr9,
        aedat,
        wtysc_clm_hdr,
        dat_fzau,
        awahr,
        kurst,
        gueen,
        _xlso_so_vald_to,
        cmnup,
        abhod,
        vkorg,
        audat,
        zuonr,
        angdt,
        vsbed,
        _xlso_payment_op,
        rep_freq,
        handle,
        _xlso_so_vald_fm,
        bstzd,
        taxk1,
        mahdt,
        bstdk,
        vbeln_grp,
        handoverloc,
        qmnum,
        kalsm_ch,
        cont_dg,
        cmfre,
        vtweg,
        telf1,
        aufnr,
        phase,
        taxk2,
        kvgr1,
        grupp,
        fsh_os_stg_change,
        abhob,
        landtx,
        kalsm,
        erdat,
        bpn,
        stage,
        kkber,
        taxk3,
        abrvw,
        vbtyp,
        kvgr2,
        knumv,
        guebg,
        fsh_vas_cg,
        waerk,
        vkbur,
        ctlpc,
        vsnmr_v,
        rplnr,
        vbklt,
        mod_allow,
        taxk4,
        _xlso_catalog_id,
        kvgr3,
        fsh_candate,
        agrzr,
        mill_appl_id,
        bsark,
        tm_ctrl_key,
        gsber
    from fields
)

select *
from final