{{ config(enabled=var('sap_using_bseg', True)) }}

{% set source_columns = adapter.get_columns_in_relation(ref('stg_sap__bseg_tmp')) %}

with base as (

    select {{ remove_slashes_from_col_names(source_columns) }}
    from {{ ref('stg_sap__bseg_tmp') }}
),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=source_columns,
                staging_columns=get_bseg_columns()
            )
        }}
    from base
),

final as (

    select
        _dataaging,
        cast(mandt as {{ dbt.type_string() }}) as mandt,
        cast(bukrs as {{ dbt.type_string() }}) as bukrs,
        cast(belnr as {{ dbt.type_string() }}) as belnr,
        cast(gjahr as {{ dbt.type_string() }}) as gjahr,
        cast(buzei as {{ dbt.type_string() }}) as buzei,
        buzei_sender,
        cast(anln1 as {{ dbt.type_string() }}) as anln1,
        cast(anln2 as {{ dbt.type_string() }}) as anln2,
        cast(aufnr as {{ dbt.type_string() }}) as aufnr,
        aplzl,
        aufpl,
        cast(augbl as {{ dbt.type_string() }}) as augbl,
        cast(augdt as {{ dbt.type_string() }}) as augdt,
        cast(ebeln as {{ dbt.type_string() }}) as ebeln,
        cast(ebelp as {{ dbt.type_string() }}) as ebelp,
        eten2,
        egbld,
        eglld,
        egrup,
        empfb,
        cast(filkd as {{ dbt.type_string() }}) as filkd,
        fcsl,
        fipos,
        fistl,
        fkont,
        gsber,
        geber,
        ghkon,
        gkart,
        gkont,
        gmvkz,
        grant_nbr,
        h_bstat,
        hbkid,
        hktid,
        koart, 
        kostl,
        maber,
        madat,

        mansp,
        manst,
        mschl,
        mwskz,
        mwsts,
        posn2,
        qbshb,
        qsfbt,
        qsshb,
        rebzg,
        samnr,
        sgtxt,
        cast(shkzg as {{ dbt.type_string() }}) as shkzg,
        cast(bschl as {{ dbt.type_string() }}) as bschl,
        skfbt,
        wskto,
        sknto,
        cast(zumsk as  {{ dbt.type_string() }}) as zumsk,
        cast(umsks as {{ dbt.type_string() }}) as umsks,
        cast(umskz as {{ dbt.type_string() }}) as umskz,
        uzawe,
        valut,
        vbel2,
        cast(vbeln as {{ dbt.type_string() }}) as vbeln,
        vbewa,
        vbund,
        vertn,
        vertt,
        vname,
        werks,
        wmwst,
        wverw, 
        xzahl, 
        zbd1p,
        zbd1t,
        zbd2p,
        zbd2t,
        zbd3t,
        zfbdt,
        zinkz,
        cast(zlsch as {{ dbt.type_string() }}) as zlsch,
        zlspr,
        zterm,
        zuonr,
        xref1,
        xref2, 
        rstgr,  
        rebzt,
        pswsl,
        pswbt,
        hkont,
        xnegp,
        zbfix,
        rfccur,
        rfzei,
        ccbtc,
        kkber,
        xref3,
        dtws1,
        dtws2,
        dtws3,
        dtws4,
        absbt, 
        projk,
        xpypr,
        bupla,
        secco, 
        pycur,
        pyamt, 
        xragl,
        cession_kz,
        buzid,
        bvtyp,
        budget_pd,
        auggj,
        bdgt_account,
        agzei,
        anfae,
        anfbj,
        anfbn,
        anfbu,
        bdiff,
        bdif2,
        bdif3,
        bewar,
        btype,
        dabrz,
        dmbtr,
        dmbt1,
        dmbt2,
        dmbt3,
        dmb21,
        dmb22,
        dmb23,
        dmb31,
        dmb32,
        dmb33,
        dmbe2,
        dmbe3,
        fkber,
        fkber_long,
        hist_tax_factor,
        hist_tax_factor1,
        hist_tax_factor2,
        hist_tax_factor3,
        imkey,
        intreno,
        j_1tpbupl,
        kstar,
        kblnr,
        kblpos,
        kidno,
        kontl,
        kontt,
        cast(kunnr as {{ dbt.type_string() }}) as kunnr,
        lifnr,
        landl,
        lzbkz,
        lwsts,
        meins,
        cast(menge as {{ dbt.type_numeric() }}) as menge,
        mwst2,
        mwst3,
        mndid,
        mwsk1,
        mwsk2,
        mwsk3,
        nplnr,
        pargb,
        pays_prov,
        pays_tran,
        payt_rsn,
        pendays,
        pfkber,
        ppdif2,
        ppdif3,
        ppdiff,
        prctr,
        pprct,
        cast(projn as {{ dbt.type_string() }}) as projn,
        qsskz,
        re_account,
        rebzj,
        rebzz,
        cast(saknr as {{ dbt.type_string() }}) as saknr,
        sknt2,
        sknt3,
        srtype,
        stceg,
        tax_country,
        tax_country1,
        tax_country2,
        tax_country3,
        txdat_from,
        txdat_from1,
        txdat_from2,
        txdat_from3,
        wrbtr,
        wrbt1,
        wrbt2,
        wrbt3,
        xanet,
        xcpdd,
        xegdr,
        xinve,
        xopvw,
        xlgclr,
        zzspreg,
        zzbuspartn,
        zzproduct,
        zzloca,
        zzchan,
        zzlob, 
        zzuserfld1,
        zzuserfld2,
        zzuserfld3,
        zzregion,
        zzstate
    from fields
)

select *
from final
