{{ config(enabled=var('sap_using_prps', True)) }}

with base as (

    select *
    from {{ ref('stg_sap__prps_tmp') }}

),

fields as (

    select
        _fivetran_deleted,
        _fivetran_synced,
        _fivetran_sap_archived,
        cast(mandt as {{ dbt.type_string() }}) as mandt,
        pspnr,
        pbukr,
        kappl,
        usr11,
        cgpl_guid16,
        isize,
        berko,
        usr09,
        sort1,
        prart,
        slwid,
        fakkz,
        usr00,
        vbeln_prps,
        psphi,
        usr02,
        plint,
        abukr,
        npfaz,
        pspri,
        logsystem,
        use05,
        use06,
        pgprf,
        aedat,
        usr05,
        stufe,
        sort2,
        scope,
        post1,
        settlementobject,
        aenam,
        xstat,
        usr01,
        clasf,
        usr03,
        astna,
        tadat,
        cgpl_objtype,
        berbu,
        akstl,
        vernr,
        sponsoredprog,
        objnr,
        berst,
        sort3,
        zschl,
        bertr,
        eew_prps_ps_dummy,
        grant_fix_assigned,
        vlpkz,
        equnr,
        jibsa,
        recid,
        otype,
        pspkz,
        kalnr,
        pgsbr,
        cgpl_logsys,
        use04,
        rgrant_nbr,
        stort,
        usr04,
        func_area,
        akokr,
        aennr,
        fkstl,
        posid_edit,
        adpsp,
        imprf,
        zuord,
        erdat,
        tplnr,
        poski,
        verna,
        ernam,
        settlmtruleinherited,
        prps_status,
        txjcd,
        grpkz,
        func_area_fix_assigned,
        etype,
        spsnr,
        vlpsp,
        ferc_ind,
        usr07,
        fkokr,
        prctr,
        loevm,
        kostl,
        klvar,
        zschm,
        fabkl,
        rfund,
        matnr,
        txtsp,
        belkz,
        fund_fix_assign,
        plakz,
        izwek,
        kalsm,
        evgew,
        cast(posid as {{ dbt.type_string() }}) as posid,
        pspnr_logs,
        pwpos,
        trmeq,
        cpd_updat,
        jibcl,
        ktrg,
        kzbws,
        settlementelement,
        vname,
        astnr,
        usr10,
        subpr,
        use07,
        fplnr,
        usr06,
        usr08,
        posnr_prps,
        kvewe,
        rfippnt,
        pkokr,
        postu,
        werks,
        abgsl,
        iumkz

    from base
)

select * from fields