{{ config(enabled=var('sap_using_cosp_bak', True)) }}

{% set source_columns = adapter.get_columns_in_relation(ref('stg_sap__cosp_bak_tmp')) %}

with base as (

    select {{ remove_slashes_from_col_names(source_columns) }}
    from {{ ref('stg_sap__cosp_bak_tmp') }}
),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=source_columns,
                staging_columns=get_cosp_bak_columns()
            )
        }}
    from base
),

final as (

    select
        cast(beknz as {{ dbt.type_string() }}) as beknz,
        cast(gjahr as {{ dbt.type_string() }}) as gjahr,
        cast(hrkft as {{ dbt.type_string() }}) as hrkft,
        cast(kstar as {{ dbt.type_string() }}) as kstar,
        cast(lednr as {{ dbt.type_string() }}) as lednr,
        cast(mandt as {{ dbt.type_string() }}) as mandt,
        cast(objnr as {{ dbt.type_string() }}) as objnr,
        cast(pargb as {{ dbt.type_string() }}) as pargb,
        cast(perbl as {{ dbt.type_string() }}) as perbl,
        cast(twaer as {{ dbt.type_string() }}) as twaer,
        cast(vbund as {{ dbt.type_string() }}) as vbund,
        cast(versn as {{ dbt.type_string() }}) as versn,
        cast(vrgng as {{ dbt.type_string() }}) as vrgng,
        cast(wrttp as {{ dbt.type_string() }}) as wrttp,
        wtg001,
        wtg002,
        wtg003,
        wtg004,
        wtg005,
        wtg006,
        wtg007,
        wtg008,
        wtg009,
        wtg010,
        wtg011,
        wtg012,
        wtg013,
        wtg014,
        wtg015,
        wtg016,
        wog001,
        wog002,
        wog003,
        wog004,
        wog005,
        wog006,
        wog007,
        wog008,
        wog009,
        wog010,
        wog011,
        wog012,
        wog013,
        wog014,
        wog015,
        wog016,
        wkg001,
        wkg002,
        wkg003,
        wkg004,
        wkg005,
        wkg006,
        wkg007,
        wkg008,
        wkg009,
        wkg010,
        wkg011,
        wkg012,
        wkg013,
        wkg014,
        wkg015,
        wkg016,
        wkf001,
        wkf002,
        wkf003,
        wkf004,
        wkf005,
        wkf006,
        wkf007,
        wkf008,
        wkf009,
        wkf010,
        wkf011,
        wkf012,
        wkf013,
        wkf014,
        wkf015,
        wkf016,
        pag001,
        pag002,
        pag003,
        pag004,
        pag005,
        pag006,
        pag007,
        pag008,
        pag009,
        pag010,
        pag011,
        pag012,
        pag013,
        pag014,
        pag015,
        pag016,
        meg001,
        meg002,
        meg003,
        meg004,
        meg005,
        meg006,
        meg007,
        meg008,
        meg009,
        meg010,
        meg011,
        meg012,
        meg013,
        meg014,
        meg015,
        meg016,
        mef001,
        mef002,
        mef003,
        mef004,
        mef005,
        mef006,
        mef007,
        mef008,
        mef009,
        mef010,
        mef011,
        mef012,
        mef013,
        mef014,
        mef015,
        mef016,
        cast(muv001 as {{ dbt.type_string() }}) as muv001,
        cast(muv002 as {{ dbt.type_string() }}) as muv002,
        cast(muv003 as {{ dbt.type_string() }}) as muv003,
        cast(muv004 as {{ dbt.type_string() }}) as muv004,
        cast(muv005 as {{ dbt.type_string() }}) as muv005,
        cast(muv006 as {{ dbt.type_string() }}) as muv006,
        cast(muv007 as {{ dbt.type_string() }}) as muv007,
        cast(muv008 as {{ dbt.type_string() }}) as muv008,
        cast(muv009 as {{ dbt.type_string() }}) as muv009,
        cast(muv010 as {{ dbt.type_string() }}) as muv010,
        cast(muv011 as {{ dbt.type_string() }}) as muv011,
        cast(muv012 as {{ dbt.type_string() }}) as muv012,
        cast(muv013 as {{ dbt.type_string() }}) as muv013,
        cast(muv014 as {{ dbt.type_string() }}) as muv014,
        cast(muv015 as {{ dbt.type_string() }}) as muv015,
        cast(muv016 as {{ dbt.type_string() }}) as muv016,
        cast(beltp as {{ dbt.type_string() }}) as beltp,
        timestmp,
        cast(bukrs as {{ dbt.type_string() }}) as bukrs,
        cast(fkber as {{ dbt.type_string() }}) as fkber,
        cast(segment as {{ dbt.type_string() }}) as segment,
        cast(geber as {{ dbt.type_string() }}) as geber,
        cast(grant_nbr as {{ dbt.type_string() }}) as grant_nbr,
        cast(budget_pd as {{ dbt.type_string() }}) as budget_pd,
        cast(meinh as {{ dbt.type_string() }}) as meinh,
        _fivetran_deleted,
        _fivetran_synced,
        _fivetran_sap_archived

    from fields

)

select * from final