{{ config(enabled=var('sap_using_acdoca', True)) }}

{% set source_columns = adapter.get_columns_in_relation(ref('stg_sap__acdoca_tmp')) %}

with base as (
    select {{ remove_slashes_from_col_names(source_columns) }}
    from {{ ref('stg_sap__acdoca_tmp') }}
),

fields as (
    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=source_columns,
                staging_columns=get_acdoca_columns()
            )
        }}
    from base
),

final as (
    select
        cast(rclnt as {{ dbt.type_string() }}) as rclnt,
        cast(ryear as {{ dbt.type_string() }}) as ryear,
        cast(belnr as {{ dbt.type_string() }}) as belnr,
        cast(rbukrs as {{ dbt.type_string() }}) as rbukrs,
        cast(rldnr as {{ dbt.type_string() }}) as rldnr,
        bttype,
        rmvct,
        rtcur,
        cast(runit as {{ dbt.type_string() }}) as runit,
        cast(aufnr as {{ dbt.type_string() }}) as aufnr,
        cast(aworg as {{ dbt.type_string() }}) as aworg,
        cast(awref as {{ dbt.type_string() }}) as awref,
        awtyp,
        autyp,
        rrcty,
        awsys,
        cast(rcntr as {{ dbt.type_string() }}) as rcntr,
        cast(rbcur as {{ dbt.type_string() }}) as rbcur,
        cast(rccur as {{ dbt.type_string() }}) as rccur,
        cast(rdcur as {{ dbt.type_string() }}) as rdcur,
        prctr,
        rbusa,
        cast(kokrs as {{ dbt.type_string() }}) as kokrs,
        segment,
        scntr,
        scope,
        pprctr,
        cast(ppaobjnr as {{ dbt.type_string() }}) as ppaobjnr,
        pps_posid,
        pps_pspid,
        sfarea,
        sbusa,
        rassc,
        rbest,
        psegment,
        qmnum,
        quant1,
        quant2,
        quant3,
        qunit1,
        qunit2,
        qunit3,
        tsl,
        drcrk,
        gjahr,
        budat,
        cast(buzei as {{ dbt.type_string() }}) as buzei,
        bwstrat,
        bschl,
        cast(bstat as {{ dbt.type_string() }}) as bstat,
        linetype,
        xsplitmod,
        usnam,
        _dataaging,
        fikrs,
        sfund,
        sgrant_nbr,
        sgtxt,
        sbudget_pd,
        re_bukrs,
        re_account,
        vname,
        egrup,
        recid,
        cast(recur as {{ dbt.type_string() }}) as recur,
        cast(mig_source as {{ dbt.type_string() }}) as mig_source,
        docln,
        mig_docln,
        cast(rhcur as {{ dbt.type_string() }}) as rhcur,
        cast(rfcur as {{ dbt.type_string() }}) as rfcur,
        cast(rvcur as {{ dbt.type_string() }}) as rvcur,
        fcsl,
        rfccur,
        cast(rkcur as {{ dbt.type_string() }}) as rkcur,
        cast(rocur as {{ dbt.type_string() }}) as rocur,
        cast(objnr as {{ dbt.type_string() }}) as objnr,
        objnr_hk,
        accas,
        cast(accasty as {{ dbt.type_string() }}) as accasty,
        cast(racct as {{ dbt.type_string() }}) as racct,
        hrkft,
        cast(vrgng as {{ dbt.type_string() }}) as vrgng,
        cast(parobsrc as {{ dbt.type_string() }}) as parobsrc,
        cast(parob1 as {{ dbt.type_string() }}) as parob1,
        paccas,
        cast(paccasty as {{ dbt.type_string() }}) as paccasty,
        cast(paobjnr as {{ dbt.type_string() }}) as paobjnr,
        paufnr,
        pautyp,
        pbukrs,
        pernr,
        uspob,
        co_beknz,
        rwcur,
        cast(co_buzei as {{ dbt.type_string() }}) as co_buzei,
        cast(co_buzei1 as {{ dbt.type_string() }}) as co_buzei1,
        cast(co_buzei2 as {{ dbt.type_string() }}) as co_buzei2,
        cast(co_buzei5 as {{ dbt.type_string() }}) as co_buzei5,
        cast(co_buzei6 as {{ dbt.type_string() }}) as co_buzei6,
        cast(co_buzei7 as {{ dbt.type_string() }}) as co_buzei7,
        cast(co_accasty_n1 as {{ dbt.type_string() }}) as co_accasty_n1,
        cast(co_accasty_n2 as {{ dbt.type_string() }}) as co_accasty_n2,
        cast(co_accasty_n3 as {{ dbt.type_string() }}) as co_accasty_n3,
        cast(poper as {{ dbt.type_string() }}) as poper,
        co_meinh,
        wsl,
        wsl2,
        wsl3,
        cast(co_osl as {{ dbt.type_numeric() }}) as co_osl,
        co_refbz,
        co_refbz1,
        co_refbz2,
        co_refbz5,
        co_refbz6,
        co_refbz7,
        co_zlenr,
        cast(hsl as {{ dbt.type_numeric() }}) as hsl,
        cast(osl as {{ dbt.type_numeric() }}) as osl,
        cast(vsl as {{ dbt.type_numeric() }}) as vsl,
        cast(bsl as {{ dbt.type_numeric() }}) as bsl,
        cast(csl as {{ dbt.type_numeric() }}) as csl,
        dabrz,
        cast(dsl as {{ dbt.type_numeric() }}) as dsl,
        ebeln,
        ebelp,
        cast(esl as {{ dbt.type_numeric() }}) as esl,
        erkrs,
        erlkz,
        cast(fsl as {{ dbt.type_numeric() }}) as fsl,
        cast(gsl as {{ dbt.type_numeric() }}) as gsl,
        cast(gkoar as {{ dbt.type_string() }}) as gkoar,
        cast(gkont as {{ dbt.type_string() }}) as gkont,
        cast(ksl as {{ dbt.type_numeric() }}) as ksl,
        kfsl,
        kfsl2,
        kfsl3,
        kdauf,
        kdpos,
        psl,
        psl2,
        psl3,
        pfsl,
        pfsl2,
        pfsl3,
        pkdauf,
        pkdpos,
        plstar,
        cast(prodper as {{ dbt.type_string() }}) as prodper,
        cast(ps_posid as {{ dbt.type_string() }}) as ps_posid,
        ps_pspid,
        pscope,
        co_megbtr,
        co_mefbtr,
        msl,
        mfsl,
        muvflg,
        beltp,
        rfarea,
        rfund,
        cast(rgcur as {{ dbt.type_string() }}) as rgcur,
        rgrant_nbr,
        rbudget_pd,
        timestamp_at,
        cast(logsyso as {{ dbt.type_string() }}) as logsyso,
        logsysp,
        cast(lstar as {{ dbt.type_string() }}) as lstar,
        matnr,
        werks,
        cast(xpaobjnr_co_rel as {{ dbt.type_string() }}) as xpaobjnr_co_rel,
        zekkn,
        _fivetran_deleted,
        _fivetran_synced
    from fields
)

select *
from final
