{{ config(enabled=var('sap_using_bsad_bck', True)) }}

{% set source_columns = adapter.get_columns_in_relation(ref('stg_sap__bsad_bck_tmp')) %}

with base as (

    select {{ remove_slashes_from_col_names(source_columns) }}
    from {{ ref('stg_sap__bsad_bck_tmp') }}
),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=source_columns,
                staging_columns=get_bsad_bck_columns()
            )
        }}
    from base
),

final as (

    select
        cast(mandt as {{ dbt.type_string() }}) as mandt,
        cast(bukrs as {{ dbt.type_string() }}) as bukrs,
        cast(kunnr as {{ dbt.type_string() }}) as kunnr,
        umsks,
        umskz,
        augdt,
        cast(augbl as {{ dbt.type_string() }}) as augbl,
        cast(zuonr as {{ dbt.type_string() }}) as zuonr,
        cast(gjahr as {{ dbt.type_string() }}) as gjahr,
        cast(belnr as {{ dbt.type_string() }}) as belnr,
        cast(buzei as {{ dbt.type_string() }}) as buzei,
        budat,
        bldat,
        cpudt,
        cast(waers as {{ dbt.type_string() }}) as waers,
        cast(blart as {{ dbt.type_string() }}) as blart,
        cast(monat as {{ dbt.type_string() }}) as monat,
        cast(bschl as {{ dbt.type_string() }}) as bschl,
        cast(zumsk as {{ dbt.type_string() }}) as zumsk,
        cast(shkzg as {{ dbt.type_string() }}) as shkzg,
        gsber,
        tax_country,
        mwskz,
        txdat_from,
        dmbtr,
        cast(wrbtr as {{ dbt.type_numeric() }}) as wrbtr,
        cast(mwsts as {{ dbt.type_numeric() }}) as mwsts,
        wmwst,
        lwsts,
        bdiff,
        bdif2,
        cast(sgtxt as {{ dbt.type_string() }}) as sgtxt,
        projn,
        aufnr,
        anln1,
        anln2,
        saknr,
        hkont,
        fkont,
        filkd,
        zfbdt,
        zterm,
        zbd1t,
        zbd2t,
        zbd3t,
        zbd1p,
        zbd2p,
        skfbt,
        cast(sknto as {{ dbt.type_numeric() }}) as sknto,
        cast(wskto as {{ dbt.type_numeric() }}) as wskto,
        cast(zlsch as {{ dbt.type_string() }}) as zlsch,
        zlspr,
        zbfix,
        hbkid,
        bvtyp,
        rebzg,
        rebzj,
        rebzz,
        samnr,
        anfbn,
        anfbj,
        anfbu,
        anfae,
        mansp,
        mschl,
        madat,
        manst,
        maber,
        xnetb,
        xanet,
        xcpdd,
        xinve,
        xzahl,
        mwsk1,
        txdat_from1,
        tax_country1,
        dmbt1,
        wrbt1,
        hist_tax_factor1,
        mwsk2,
        txdat_from2,
        tax_country2,
        dmbt2,
        wrbt2,
        hist_tax_factor2,
        mwsk3,
        txdat_from3,
        tax_country3,
        dmbt3,
        wrbt3,
        hist_tax_factor3,
        hist_tax_factor,
        bstat,
        vbund,
        vbeln,
        rebzt,
        infae,
        stceg,
        egbld,
        eglld,
        rstgr,
        xnoza,
        vertt,
        vertn,
        vbewa,
        wverw,
        projk,
        fipos,
        nplnr,
        aufpl,
        aplzl,
        xegdr,
        dmbe2,
        dmbe3,
        dmb21,
        dmb22,
        dmb23,
        dmb31,
        dmb32,
        dmb33,
        bdif3,
        xragl,
        uzawe,
        xstov,
        mwst2,
        mwst3,
        sknt2,
        sknt3,
        xref1,
        xref2,
        xarch,
        pswsl,
        pswbt,
        lzbkz,
        landl,
        imkey,
        vbel2,
        vpos2,
        posn2,
        eten2,
        fistl,
        geber,
        dabrz,
        xnegp,
        kostl,
        rfzei,
        kkber,
        empfb,
        prctr,
        xref3,
        qsskz,
        zinkz,
        dtws1,
        dtws2,
        dtws3,
        dtws4,
        xpypr,
        kidno,
        absbt,
        ccbtc,
        pycur,
        pyamt,
        bupla,
        secco,
        cession_kz,
        ppdiff,
        ppdif2,
        ppdif3,
        kblnr,
        kblpos,
        grant_nbr,
        gmvkz,
        srtype,
        lotkz,
        fkber,
        intreno,
        pprct,
        buzid,
        auggj,
        hktid,
        budget_pd,
        pays_prov,
        pays_tran,
        mndid,
        _dataaging,
        kontt,
        kontl,
        uebgdat,
        vname,
        egrup,
        btype,
        propmano,
        gkont,
        gkart,
        ghkon,
        _fivetran_synced
    from fields
)

select *
from final