{{ config(enabled=var('sap_using_matdoc', True)) }}

{% set source_columns = adapter.get_columns_in_relation(ref('stg_sap__matdoc_tmp')) %}

with base as (

    select {{ remove_slashes_from_col_names(source_columns) }}
    from {{ ref('stg_sap__matdoc_tmp') }}
),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=source_columns,
                staging_columns=get_matdoc_columns()
            )
        }}
    from base
),

final as (
    select
        mandt,                
        mblnr,                
        mjahr,                
        zeile,                
        line_id,              
        parent_id,            
        line_depth,           
        maa_urzei,            
        bwart,                
        xauto,                
        matnr,                
        werks,                
        lgort,                
        charg,                
        insmk,                
        zusch,                
        zustd,                
        sobkz,                
        lifnr,                
        kunnr,                
        kdauf,                
        kdpos,                
        kdein,  
        plpla,  
        shkzg,  
        waers,  
        dmbtr,  
        bnbtr,  
        bualt,  
        shkum,  
        dmbum,  
        bwtar,  
        menge,  
        meins,  
        erfmg,  
        erfme,  
        bpmng,  
        bprme,  
        ebeln,  
        ebelp,  
        lfbja,  
        lfbnr,  
        lfpos,  
        sjahr,  
        smbln,  
        smblp,  
        elikz,  
        sgtxt,   
        equnr,   
        wempf,   
        ablad,   
        gsber,   
        kokrs,   
        pargb,   
        parbu,   
        kostl,   
        projn,   
        aufnr,   
        anln1,   
        anln2,   
        xskst,   
        xsauf,   
        xspro,   
        xserg,   
        gjahr,   
        xruem,   
        xruej,   
        bukrs,   
        belnr,   
        buzei,   
        belum,   
        buzum,   
        rsnum,   
        rspos,   
        kzear,   
        pbamg,   
        kzstr,   
        ummat,   
        umwrk,   
        umlgo,   
        umcha,   
        umzst,   
        umzus,   
        umbar,   
        umsok,   
        kzbew,   
        kzvbr,   
        kzzug,   
        weunb,   
        palan,   
        lgnum,   
        lgtyp,   
        lgpla,   
        bestq,   
        bwlvs,   
        tbnum,   
        tbpos,   
        xblvs,       
        vschn,       
        nschn,       
        dypla,       
        ubnum,       
        tbpri,       
        tanum,       
        weanz,       
        grund,       
        evers,       
        evere,       
        imkey,       
        kstrg,       
        paobjnr,     
        prctr,       
        ps_psp_pnr,  
        nplnr,       
        aufpl,       
        aplzl,       
        aufps,       
        vptnr,       
        fipos,       
        sakto,       
        bstmg,       
        bstme,       
        xwsbr,                
        emlif,                
        dummy_incl_eew_cobl,  
        exbwr,                
        vkwrt,                
        aktnr,                
        zekkn,                
        vfdat,                
        cuobj_ch,             
        exvkw,                
        pprctr,               
        rsart,                
        geber,                
        fistl,                
        matbf,                
        ummab,                
        bustm,                
        bustw,                
        mengu,                
        wertu,                
        lbkum,                
        salk3,                
        vprsv,                
        fkber,                
        dabrbz,     
        vkwra,      
        dabrz,      
        xbeau,      
        lsmng,      
        lsmeh,      
        kzbws,      
        qinspst,    
        urzei,      
        j_1bexbase, 
        mwskz,      
        txjcd,      
        ematn,      
        j_1agirupd, 
        vkmws,      
        hsdat,      
        berkz,      
        mat_kdauf,  
        mat_kdpos,  
        mat_pspnr,  
        xwoff,      
        bemot,      
        prznr,      
        llief,      
        lstar,                   
        xobew,                   
        grant_nbr,               
        zustd_t156m,             
        spe_gts_stock_ty,        
        kblnr,                   
        kblpos,                  
        xmacc,                   
        vgart as vgart_mkpf,   
        budat as budat_mkpf,   
        cpudt as cpudt_mkpf,   
        cputm as cputm_mkpf,   
        usnam as usnam_mkpf,   
        xblnr as xblnr_mkpf,   
        tcode2 as tcode2_mkpf, 
        vbeln_im,                
        vbelp_im,                
        sgt_scat,                
        sgt_umscat,              
        sgt_rcat,                
        serviceperformer,        
        pernr,                   
        knttp_gr,                
        work_item_id,            
        fbuda,                   
        xprint,                   
        nroflabels,               
        _cwm_menge,               
        _cwm_meins,               
        _cwm_erfmg,               
        _cwm_erfme,               
        service_doc_type,         
        service_doc_id,           
        service_doc_item_id,      
        ewm_lgnum,                
        ewm_gmdoc,                
        resourcename_sid,         
        resourcename_cid,         
        dummy_matdoc_incl_eew_ps, 
        disub_owner,              
        fsh_season_year,          
        fsh_season,               
        fsh_collection,           
        fsh_theme,                
        '' as fsh_umsea_yr,               
        '' as fsh_umsea,                  
        '' as fsh_umcoll,                 
        '' as fsh_umtheme,                
        '' as sgt_chint,                  
        compl_mark,            
        fzgls_mark,            
        etanp_mark,            
        popup_mark,            
        oinavnw,               
        oicondcod,             
        condi,                 
        wrf_charstc1,          
        wrf_charstc2,          
        wrf_charstc3,
        vgart,	
        blart,	
        blaum,	
        bldat,	
        budat,	
        cpudt,	
        cputm,	
        aedat,	
        usnam,	
        tcode,	
        xblnr,	
        bktxt,	
        frath,	
        frbnr,	
        wever,
        xabln,	
        awsys,	
        bla2d,	
        tcode2,	
        bfwms,	
        exnum,	
        spe_budat_uhr,	
        spe_budat_zone,	
        le_vbeln,	
        spe_logsys,	
        spe_mdnum_ewm,	
        gts_cusref_no,	
        fls_rsto,	
        msr_active,	
        knumv,	
        xcompl
    from fields
)

select *
from final
