{{ config(enabled=var('sap_using_ekko', True)) }}

with base as (
    select *
    from {{ ref('stg_sap__ekko_tmp') }}
),

fields as (
    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=adapter.get_columns_in_relation(ref('stg_sap__ekko_tmp')),
                staging_columns=get_ekko_columns()
            )
        }}
    from base
),

final as (
    select
        abgru,
        absgr,
        addnr,
        adrnr,
        aedat,
        angdt,
        angnr,
        aurel_allow,
        ausnr,
        autlf,
        bedat,
        bnddt,
        bsakz,
        bsart,
        bstyp,
        bwbdt,
        budg_type,
        cast(bukrs as {{ dbt.type_string() }}) as bukrs,
        check_type,
        con_distr_lev,
        con_otb_req,
        con_prebook_lev,
        contract_allow,
        delper_allow,
        description,
        dpamt,
        dpdat,
        dppct,
        dptyp,
        ebeln,
        eindt,
        eindt_allow,
        ekgrp,
        ekgrp_allow,
        ekorg,
        eq_eindt,
        eq_werks,
        ernam,
        exnum,
        fixpo,
        fixpo_allow,
        force_cnt,
        force_id,
        frggr,
        frgke,
        frgrl,
        frgsx,
        frgzu,
        fsh_item_group,
        fsh_os_stg_change,
        fsh_snst_status,
        fsh_transaction,
        fsh_vas_last_item,
        gwldt,
        handoverloc,
        hierarchy_exists,
        hvr_change_time,
        hvr_is_deleted,
        ihran,
        ihrez,
        inco1,
        inco2,
        inco2_l,
        inco3_l,
        incov,
        kalsm,
        kdatb,
        kdate,
        key_id,
        key_id_allow,
        knumv,
        konnr,
        kornr,
        ktwrt,
        kufix,
        kunnr,
        lands,
        lblif,
        legal_contract,
        lifnr,
        lifre,
        llief,
        loekz,
        logsy,
        lphis,
        lponr,
        ltsnr_allow,
        cast(mandt as {{ dbt.type_string() }}) as mandt,
        memory,
        memorytype,
        msr_id,
        otb_cond_type,
        otb_curr,
        otb_level,
        otb_reason,
        otb_res_value,
        otb_spec_value,
        otb_status,
        otb_value,
        pincr,
        pohf_type,
        procstat,
        pstyp_allow,
        release_date,
        reason_code,
        reloc_id,
        reloc_seq_id,
        reswk,
        retpc,
        rettp,
        revno,
        rlwrt,
        scmproc,
        shipcond,
        source_logsys,
        spr_rsn_profile,
        spras,
        stafo,
        stako,
        statu,
        stceg,
        stceg_l,
        submi,
        telf1,
        threshold_exists,
        unsez,
        upinc,
        verkf,
        vsart,
        vzskz,
        waers,
        weakt,
        werks_allow,
        wkurs,
        zbd1p,
        zbd1t,
        zbd2p,
        zbd2t,
        zbd3t,
        zterm
    from fields
)

select *
from final
