{% macro get_mchb_columns() %}

{% set columns = [
    {"name": "_cwm_ceinm", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cinsm", "datatype": dbt.type_numeric()},
    {"name": "_cwm_clabs", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cretm", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cspem", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cumlm", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cvmei", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cvmin", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cvmla", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cvmre", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cvmsp", "datatype": dbt.type_numeric()},
    {"name": "_cwm_cvmum", "datatype": dbt.type_numeric()},
    {"name": "_fivetran_deleted", "datatype": dbt.type_boolean()},
    {"name": "_fivetran_sap_archived", "datatype": dbt.type_boolean()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "aenam", "datatype": dbt.type_string()},
    {"name": "ceinm", "datatype": dbt.type_numeric()},
    {"name": "charg", "datatype": dbt.type_string()},
    {"name": "chdll", "datatype": "date"},
    {"name": "chjin", "datatype": dbt.type_string()},
    {"name": "chrue", "datatype": dbt.type_string()},
    {"name": "cinsm", "datatype": dbt.type_numeric()},
    {"name": "clabs", "datatype": dbt.type_numeric()},
    {"name": "cretm", "datatype": dbt.type_numeric()},
    {"name": "cspem", "datatype": dbt.type_numeric()},
    {"name": "cumlm", "datatype": dbt.type_numeric()},
    {"name": "cvmei", "datatype": dbt.type_numeric()},
    {"name": "cvmin", "datatype": dbt.type_numeric()},
    {"name": "cvmla", "datatype": dbt.type_numeric()},
    {"name": "cvmre", "datatype": dbt.type_numeric()},
    {"name": "cvmsp", "datatype": dbt.type_numeric()},
    {"name": "cvmum", "datatype": dbt.type_numeric()},
    {"name": "ernam", "datatype": dbt.type_string()},
    {"name": "ersda", "datatype": "date"},
    {"name": "fsh_collection", "datatype": dbt.type_string()},
    {"name": "fsh_salloc_qty", "datatype": dbt.type_numeric()},
    {"name": "fsh_season", "datatype": dbt.type_string()},
    {"name": "fsh_season_year", "datatype": dbt.type_string()},
    {"name": "fsh_theme", "datatype": dbt.type_string()},
    {"name": "herkl", "datatype": dbt.type_string()},
    {"name": "kzice", "datatype": dbt.type_string()},
    {"name": "kzicl", "datatype": dbt.type_string()},
    {"name": "kzicq", "datatype": dbt.type_string()},
    {"name": "kzics", "datatype": dbt.type_string()},
    {"name": "kzvce", "datatype": dbt.type_string()},
    {"name": "kzvcl", "datatype": dbt.type_string()},
    {"name": "kzvcq", "datatype": dbt.type_string()},
    {"name": "kzvcs", "datatype": dbt.type_string()},
    {"name": "laeda", "datatype": "date"},
    {"name": "lfgja", "datatype": dbt.type_string()},
    {"name": "lfmon", "datatype": dbt.type_string()},
    {"name": "lgort", "datatype": dbt.type_string()},
    {"name": "lvorm", "datatype": dbt.type_string()},
    {"name": "mandt", "datatype": dbt.type_string()},
    {"name": "matnr", "datatype": dbt.type_string()},
    {"name": "sgt_scat", "datatype": dbt.type_string()},
    {"name": "sperc", "datatype": dbt.type_string()},
    {"name": "werks", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}