{% macro get_t161_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_rowid", "datatype": dbt.type_numeric()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "abgebot", "datatype": dbt.type_string()},
    {"name": "abvor", "datatype": dbt.type_string()},
    {"name": "ar_object", "datatype": dbt.type_string()},
    {"name": "brefn", "datatype": dbt.type_string()},
    {"name": "bsakz", "datatype": dbt.type_string()},
    {"name": "bsart", "datatype": dbt.type_string()},
    {"name": "bstyp", "datatype": dbt.type_string()},
    {"name": "cp_aktive", "datatype": dbt.type_string()},
    {"name": "cptype", "datatype": dbt.type_string()},
    {"name": "fls_rsto", "datatype": dbt.type_string()},
    {"name": "fsh_dpr_detpro", "datatype": dbt.type_string()},
    {"name": "fsh_excl_return", "datatype": dbt.type_string()},
    {"name": "fsh_po_idoc", "datatype": dbt.type_string()},
    {"name": "fsh_var_kalsm", "datatype": dbt.type_string()},
    {"name": "fsh_vas_act", "datatype": dbt.type_string()},
    {"name": "fsh_vas_del", "datatype": dbt.type_string()},
    {"name": "fsh_vas_detdt", "datatype": dbt.type_string()},
    {"name": "fsh_vas_kalsm", "datatype": dbt.type_string()},
    {"name": "gsfrg", "datatype": dbt.type_string()},
    {"name": "hityp", "datatype": dbt.type_string()},
    {"name": "hvr_change_time", "datatype": dbt.type_string()},
    {"name": "hvr_is_deleted", "datatype": dbt.type_string()},
    {"name": "koako", "datatype": dbt.type_string()},
    {"name": "koett", "datatype": dbt.type_string()},
    {"name": "kornr", "datatype": dbt.type_string()},
    {"name": "kzale", "datatype": dbt.type_string()},
    {"name": "lphis", "datatype": dbt.type_string()},
    {"name": "mandt", "datatype": dbt.type_string()},
    {"name": "mill_omkz", "datatype": dbt.type_string()},
    {"name": "msr_active", "datatype": dbt.type_string()},
    {"name": "numka", "datatype": dbt.type_string()},
    {"name": "numkc", "datatype": dbt.type_string()},
    {"name": "numke", "datatype": dbt.type_string()},
    {"name": "numki", "datatype": dbt.type_string()},
    {"name": "oicsegi", "datatype": dbt.type_string()},
    {"name": "oirfqreq", "datatype": dbt.type_string()},
    {"name": "pargr", "datatype": dbt.type_string()},
    {"name": "pincr", "datatype": dbt.type_string()},
    {"name": "refba", "datatype": dbt.type_string()},
    {"name": "rdp_profile", "datatype": dbt.type_string()},
    {"name": "shenq", "datatype": dbt.type_string()},
    {"name": "stafo", "datatype": dbt.type_string()},
    {"name": "stako", "datatype": dbt.type_string()},
    {"name": "tolsl", "datatype": dbt.type_string()},
    {"name": "umlif", "datatype": dbt.type_string()},
    {"name": "upinc", "datatype": dbt.type_string()},
    {"name": "variante", "datatype": dbt.type_string()},
    {"name": "wrf_enable_dateline", "datatype": dbt.type_string()},
    {"name": "wvvkz", "datatype": dbt.type_string()},
    {"name": "xlokz", "datatype": dbt.type_string()},
    {"name": "/sapmp/atnam", "datatype": dbt.type_string(), "alias": "_sapmp_atnam", "quote": true},
    {"name": "/sapmp/ceact", "datatype": dbt.type_string(), "alias": "_sapmp_ceact", "quote": true},
    {"name": "/sapmp/gauf", "datatype": dbt.type_string(), "alias": "_sapmp_gauf", "quote": true},
    {"name": "/sapmp/pdact", "datatype": dbt.type_string(), "alias": "_sapmp_pdact", "quote": true},
    {"name": "/sapmp/pprot", "datatype": dbt.type_string(), "alias": "_sapmp_pprot", "quote": true},
    {"name": "/sapmp/puser", "datatype": dbt.type_string(), "alias": "_sapmp_puser", "quote": true},
    {"name": "/sapmp/pausw", "datatype": dbt.type_string(), "alias": "_sapmp_pausw", "quote": true}
] %}

{{ return(columns) }}

{% endmacro %}

