{% macro get_faat_plan_values_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "aafag", "datatype": dbt.type_numeric()},
    {"name": "aafap", "datatype": dbt.type_numeric()},
    {"name": "aafaz", "datatype": dbt.type_numeric()},
    {"name": "afaber", "datatype": dbt.type_string()},
    {"name": "afasl", "datatype": dbt.type_string()},
    {"name": "afbnr", "datatype": dbt.type_string()},
    {"name": "anln1", "datatype": dbt.type_string()},
    {"name": "anln2", "datatype": dbt.type_string()},
    {"name": "answl", "datatype": dbt.type_numeric()},
    {"name": "anupd", "datatype": dbt.type_string()},
    {"name": "aufng", "datatype": dbt.type_numeric()},
    {"name": "aufnp", "datatype": dbt.type_numeric()},
    {"name": "aufnz", "datatype": dbt.type_numeric()},
    {"name": "aufwb", "datatype": dbt.type_numeric()},
    {"name": "aufwp", "datatype": dbt.type_numeric()},
    {"name": "aufwz", "datatype": dbt.type_numeric()},
    {"name": "belnr", "datatype": dbt.type_string()},
    {"name": "budget_pd", "datatype": dbt.type_string()},
    {"name": "budget_pd2", "datatype": dbt.type_string()},
    {"name": "bukrs", "datatype": dbt.type_string()},
    {"name": "caufn", "datatype": dbt.type_string()},
    {"name": "fistl", "datatype": dbt.type_string()},
    {"name": "fistl2", "datatype": dbt.type_string()},
    {"name": "fkber", "datatype": dbt.type_string()},
    {"name": "fkber2", "datatype": dbt.type_string()},
    {"name": "geber", "datatype": dbt.type_string()},
    {"name": "geber2", "datatype": dbt.type_string()},
    {"name": "gjahr", "datatype": dbt.type_string()},
    {"name": "grant_nbr", "datatype": dbt.type_string()},
    {"name": "grant_nbr2", "datatype": dbt.type_string()},
    {"name": "gsber", "datatype": dbt.type_string()},
    {"name": "imkey", "datatype": dbt.type_string()},
    {"name": "invzm", "datatype": dbt.type_numeric()},
    {"name": "kostl", "datatype": dbt.type_string()},
    {"name": "lstar", "datatype": dbt.type_string()},
    {"name": "mafag", "datatype": dbt.type_numeric()},
    {"name": "mafap", "datatype": dbt.type_numeric()},
    {"name": "mafaz", "datatype": dbt.type_numeric()},
    {"name": "mandt", "datatype": dbt.type_string()},
    {"name": "nafag", "datatype": dbt.type_numeric()},
    {"name": "nafap", "datatype": dbt.type_numeric()},
    {"name": "nafaz", "datatype": dbt.type_numeric()},
    {"name": "peraf", "datatype": dbt.type_string()},
    {"name": "prctr", "datatype": dbt.type_string()},
    {"name": "ps_psp_pnr2", "datatype": dbt.type_string()},
    {"name": "safag", "datatype": dbt.type_numeric()},
    {"name": "safap", "datatype": dbt.type_numeric()},
    {"name": "safaz", "datatype": dbt.type_numeric()},
    {"name": "segment", "datatype": dbt.type_string()},
    {"name": "xunul", "datatype": dbt.type_string()},
    {"name": "zinsg", "datatype": dbt.type_numeric()},
    {"name": "zinsp", "datatype": dbt.type_numeric()},
    {"name": "zinsz", "datatype": dbt.type_numeric()},
    {"name": "zucod", "datatype": dbt.type_string()},
    {"name": "zujhr", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}
