{% macro get_tka01_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": dbt.type_boolean()},
    {"name": "_fivetran_sap_archived", "datatype": dbt.type_boolean()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "alemt", "datatype": dbt.type_string()},
    {"name": "auth_ke_no_std", "datatype": dbt.type_string()},
    {"name": "auth_ke_use_add1", "datatype": dbt.type_string()},
    {"name": "auth_ke_use_add2", "datatype": dbt.type_string()},
    {"name": "auth_use_add1", "datatype": dbt.type_string()},
    {"name": "auth_use_add2", "datatype": dbt.type_string()},
    {"name": "auth_use_no_std", "datatype": dbt.type_string()},
    {"name": "bezei", "datatype": dbt.type_string()},
    {"name": "blart", "datatype": dbt.type_string()},
    {"name": "bphinr", "datatype": dbt.type_string()},
    {"name": "ctyp", "datatype": dbt.type_string()},
    {"name": "cvact", "datatype": dbt.type_string()},
    {"name": "cvprof", "datatype": dbt.type_string()},
    {"name": "defprctr", "datatype": dbt.type_string()},
    {"name": "dprct", "datatype": dbt.type_string()},
    {"name": "erkrs", "datatype": dbt.type_string()},
    {"name": "f_obsolete", "datatype": dbt.type_string()},
    {"name": "fikrs", "datatype": dbt.type_string()},
    {"name": "khinr", "datatype": dbt.type_string()},
    {"name": "kokfi", "datatype": dbt.type_string()},
    {"name": "kokrs", "datatype": dbt.type_string()},
    {"name": "komp0", "datatype": dbt.type_string()},
    {"name": "komp1", "datatype": dbt.type_string()},
    {"name": "komp2", "datatype": dbt.type_string()},
    {"name": "kstar_fid", "datatype": dbt.type_string()},
    {"name": "kstar_fin", "datatype": dbt.type_string()},
    {"name": "ktopl", "datatype": dbt.type_string()},
    {"name": "leading_fsv", "datatype": dbt.type_string()},
    {"name": "lmona", "datatype": dbt.type_string()},
    {"name": "logsystem", "datatype": dbt.type_string()},
    {"name": "mandt", "datatype": dbt.type_string()},
    {"name": "md_logsystem", "datatype": dbt.type_string()},
    {"name": "objcur_curdt", "datatype": dbt.type_string()},
    {"name": "objcur_kurst", "datatype": dbt.type_string()},
    {"name": "objcur_srcal", "datatype": dbt.type_string()},
    {"name": "objcur_srcct", "datatype": dbt.type_string()},
    {"name": "objcur_use", "datatype": dbt.type_string()},
    {"name": "pca_acc_diff", "datatype": dbt.type_string()},
    {"name": "pca_alemt", "datatype": dbt.type_string()},
    {"name": "pca_valu", "datatype": dbt.type_string()},
    {"name": "pcacur", "datatype": dbt.type_string()},
    {"name": "pcacurtp", "datatype": dbt.type_string()},
    {"name": "pcatrcur", "datatype": dbt.type_string()},
    {"name": "pcbel", "datatype": dbt.type_string()},
    {"name": "pcldg", "datatype": dbt.type_string()},
    {"name": "phinr", "datatype": dbt.type_string()},
    {"name": "rcl_primac", "datatype": dbt.type_string()},
    {"name": "rclac", "datatype": dbt.type_string()},
    {"name": "tp_valohb", "datatype": dbt.type_string()},
    {"name": "vname", "datatype": dbt.type_string()},
    {"name": "waers", "datatype": dbt.type_string()},
    {"name": "xbpale", "datatype": dbt.type_string()},
    {"name": "xwbuk", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}