{{ config(enabled=var('sap_using_bsad_bck', True) and var('sap_using_bseg', True) and var('sap_using_bkpf', True)) }}

with stg_sap__bsad_bck as (
  select *
  from {{ ref('stg_sap__bsad_bck') }}
),

stg_sap__bseg as (
  select *
  from {{ ref('stg_sap__bseg') }}
),

stg_sap__bkpf as (
  select *
  from {{ ref('stg_sap__bkpf') }}
),

archived_records as (
  select
    cast(b.mandt as {{ dbt.type_string() }}) as mandt,
    cast(b.bukrs as {{ dbt.type_string() }}) as bukrs,
    cast(b.kunnr as {{ dbt.type_string() }}) as kunnr,
    cast(b.umsks as {{ dbt.type_string() }}) as umsks,
    cast(b.umskz as {{ dbt.type_string() }}) as umskz,
    cast(b.augdt as {{ dbt.type_string() }}) as augdt,
    cast(b.augbl as {{ dbt.type_string() }}) as augbl,
    cast(b.zuonr as {{ dbt.type_string() }}) as zuonr,
    cast(b.gjahr as {{ dbt.type_string() }}) as gjahr,
    cast(b.belnr as {{ dbt.type_string() }}) as belnr,
    cast(b.buzei as {{ dbt.type_string() }}) as buzei,
    cast(b.budat as {{ dbt.type_string() }}) as budat,
    cast(b.bldat as {{ dbt.type_string() }}) as bldat,
    cast(b.cpudt as {{ dbt.type_string() }}) as cpudt,
    cast(b.waers as {{ dbt.type_string() }}) as waers,
    cast('' as {{ dbt.type_string() }}) as xblnr,
    cast(b.blart as {{ dbt.type_string() }}) as blart,
    cast(b.monat as {{ dbt.type_string() }}) as monat,
    cast(b.bschl as {{ dbt.type_string() }}) as bschl,
    cast(b.zumsk as {{ dbt.type_string() }}) as zumsk,
    cast(b.shkzg as {{ dbt.type_string() }}) as shkzg,
    cast(b.gsber as {{ dbt.type_string() }}) as gsber,
    cast(b.tax_country as {{ dbt.type_string() }}) as tax_country,
    cast(b.mwskz as {{ dbt.type_string() }}) as mwskz,
    cast(b.txdat_from as {{ dbt.type_string() }}) as txdat_from,
    cast(b.dmbtr as {{ dbt.type_numeric() }}) as dmbtr,
    cast(b.wrbtr as {{ dbt.type_numeric() }}) as wrbtr,
    cast(0 as {{ dbt.type_numeric() }}) as fcsl,
    cast('' as {{ dbt.type_string() }}) as rfccur,
    cast(b.mwsts as {{ dbt.type_numeric() }}) as mwsts,
    cast(b.wmwst as {{ dbt.type_numeric() }}) as wmwst,
    cast(b.lwsts as {{ dbt.type_numeric() }}) as lwsts,
    cast(b.bdiff as {{ dbt.type_numeric() }}) as bdiff,
    cast(b.bdif2 as {{ dbt.type_numeric() }}) as bdif2,
    cast(b.sgtxt as {{ dbt.type_string() }}) as sgtxt,
    cast(b.projn as {{ dbt.type_string() }}) as projn,
    cast(b.aufnr as {{ dbt.type_string() }}) as aufnr,
    cast(b.anln1 as {{ dbt.type_string() }}) as anln1,
    cast(b.anln2 as {{ dbt.type_string() }}) as anln2,
    cast(b.saknr as {{ dbt.type_string() }}) as saknr,
    cast(b.hkont as {{ dbt.type_string() }}) as hkont,
    cast(b.fkont as {{ dbt.type_string() }}) as fkont,
    cast(b.filkd as {{ dbt.type_string() }}) as filkd,
    cast(b.zfbdt as {{ dbt.type_string() }}) as zfbdt,
    cast(b.zterm as {{ dbt.type_string() }}) as zterm,
    cast(b.zbd1t as {{ dbt.type_numeric() }}) as zbd1t,
    cast(b.zbd2t as {{ dbt.type_numeric() }}) as zbd2t,
    cast(b.zbd3t as {{ dbt.type_numeric() }}) as zbd3t,
    cast(b.zbd1p as {{ dbt.type_numeric() }}) as zbd1p,
    cast(b.zbd2p as {{ dbt.type_numeric() }}) as zbd2p,
    cast(b.skfbt as {{ dbt.type_numeric() }}) as skfbt,
    cast(b.sknto as {{ dbt.type_numeric() }}) as sknto,
    cast(b.wskto as {{ dbt.type_numeric() }}) as wskto,
    cast(b.zlsch as {{ dbt.type_string() }}) as zlsch,
    cast(b.zlspr as {{ dbt.type_string() }}) as zlspr,
    cast(b.zbfix as {{ dbt.type_string() }}) as zbfix,
    cast(b.hbkid as {{ dbt.type_string() }}) as hbkid,
    cast(b.bvtyp as {{ dbt.type_string() }}) as bvtyp,
    cast(b.rebzg as {{ dbt.type_string() }}) as rebzg,
    cast(b.rebzj as {{ dbt.type_string() }}) as rebzj,
    cast(b.rebzz as {{ dbt.type_string() }}) as rebzz,
    cast(b.samnr as {{ dbt.type_string() }}) as samnr,
    cast(b.anfbn as {{ dbt.type_string() }}) as anfbn,
    cast(b.anfbj as {{ dbt.type_string() }}) as anfbj,
    cast(b.anfbu as {{ dbt.type_string() }}) as anfbu,
    cast(b.anfae as {{ dbt.type_string() }}) as anfae,
    cast(b.mansp as {{ dbt.type_string() }}) as mansp,
    cast(b.mschl as {{ dbt.type_string() }}) as mschl,
    cast(b.madat as {{ dbt.type_string() }}) as madat,
    cast(b.manst as {{ dbt.type_string() }}) as manst,
    cast(b.maber as {{ dbt.type_string() }}) as maber,
    cast(b.xnetb as {{ dbt.type_string() }}) as xnetb,
    cast(b.xanet as {{ dbt.type_string() }}) as xanet,
    cast(b.xcpdd as {{ dbt.type_string() }}) as xcpdd,
    cast(b.xinve as {{ dbt.type_string() }}) as xinve,
    cast(b.xzahl as {{ dbt.type_string() }}) as xzahl,
    cast(b.mwsk1 as {{ dbt.type_string() }}) as mwsk1,
    cast(b.txdat_from1 as {{ dbt.type_string() }}) as txdat_from1,
    cast(b.tax_country1 as {{ dbt.type_string() }}) as tax_country1,
    cast(b.dmbt1 as {{ dbt.type_numeric() }}) as dmbt1,
    cast(b.wrbt1 as {{ dbt.type_numeric() }}) as wrbt1,
    cast(b.hist_tax_factor1 as {{ dbt.type_string() }}) as hist_tax_factor1,
    cast(b.mwsk2 as {{ dbt.type_string() }}) as mwsk2,
    cast(b.txdat_from2 as {{ dbt.type_string() }}) as txdat_from2,
    cast(b.tax_country2 as {{ dbt.type_string() }}) as tax_country2,
    cast(b.dmbt2 as {{ dbt.type_numeric() }}) as dmbt2,
    cast(b.wrbt2 as {{ dbt.type_numeric() }}) as wrbt2,
    cast(b.hist_tax_factor2 as {{ dbt.type_string() }}) as hist_tax_factor2,
    cast(b.mwsk3 as {{ dbt.type_string() }}) as mwsk3,
    cast(b.txdat_from3 as {{ dbt.type_string() }}) as txdat_from3,
    cast(b.tax_country3 as {{ dbt.type_string() }}) as tax_country3,
    cast(b.dmbt3 as {{ dbt.type_numeric() }}) as dmbt3,
    cast(b.wrbt3 as {{ dbt.type_numeric() }}) as wrbt3,
    cast(b.hist_tax_factor3 as {{ dbt.type_string() }}) as hist_tax_factor3,
    cast(b.hist_tax_factor as {{ dbt.type_string() }}) as hist_tax_factor,
    cast(b.bstat as {{ dbt.type_string() }}) as bstat,
    cast(b.vbund as {{ dbt.type_string() }}) as vbund,
    cast(b.vbeln as {{ dbt.type_string() }}) as vbeln,
    cast(b.rebzt as {{ dbt.type_string() }}) as rebzt,
    cast(b.infae as {{ dbt.type_string() }}) as infae,
    cast(b.stceg as {{ dbt.type_string() }}) as stceg,
    cast(b.egbld as {{ dbt.type_string() }}) as egbld,
    cast(b.eglld as {{ dbt.type_string() }}) as eglld,
    cast(b.rstgr as {{ dbt.type_string() }}) as rstgr,
    cast(b.xnoza as {{ dbt.type_string() }}) as xnoza,
    cast(b.vertt as {{ dbt.type_string() }}) as vertt,
    cast(b.vertn as {{ dbt.type_string() }}) as vertn,
    cast(b.vbewa as {{ dbt.type_string() }}) as vbewa,
    cast(b.wverw as {{ dbt.type_string() }}) as wverw,
    cast(b.projk as {{ dbt.type_string() }}) as projk,
    cast(b.fipos as {{ dbt.type_string() }}) as fipos,
    cast(b.nplnr as {{ dbt.type_string() }}) as nplnr,
    cast(b.aufpl as {{ dbt.type_string() }}) as aufpl,
    cast(b.aplzl as {{ dbt.type_string() }}) as aplzl,
    cast(b.xegdr as {{ dbt.type_string() }}) as xegdr,
    cast(b.dmbe2 as {{ dbt.type_numeric() }}) as dmbe2,
    cast(b.dmbe3 as {{ dbt.type_numeric() }}) as dmbe3,
    cast(b.dmb21 as {{ dbt.type_numeric() }}) as dmb21,
    cast(b.dmb22 as {{ dbt.type_numeric() }}) as dmb22,
    cast(b.dmb23 as {{ dbt.type_numeric() }}) as dmb23,
    cast(b.dmb31 as {{ dbt.type_numeric() }}) as dmb31,
    cast(b.dmb32 as {{ dbt.type_numeric() }}) as dmb32,
    cast(b.dmb33 as {{ dbt.type_numeric() }}) as dmb33,
    cast(b.bdif3 as {{ dbt.type_numeric() }}) as bdif3,
    cast(b.xragl as {{ dbt.type_string() }}) as xragl,
    cast(b.uzawe as {{ dbt.type_string() }}) as uzawe,
    cast(b.xstov as {{ dbt.type_string() }}) as xstov,
    cast(b.mwst2 as {{ dbt.type_numeric() }}) as mwst2,
    cast(b.mwst3 as {{ dbt.type_numeric() }}) as mwst3,
    cast(b.sknt2 as {{ dbt.type_numeric() }}) as sknt2,
    cast(b.sknt3 as {{ dbt.type_numeric() }}) as sknt3,
    cast(b.xref1 as {{ dbt.type_string() }}) as xref1,
    cast(b.xref2 as {{ dbt.type_string() }}) as xref2,
    cast(b.xarch as {{ dbt.type_string() }}) as xarch,
    cast(b.pswsl as {{ dbt.type_string() }}) as pswsl,
    cast(b.pswbt as {{ dbt.type_numeric() }}) as pswbt,
    cast(b.lzbkz as {{ dbt.type_string() }}) as lzbkz,
    cast(b.landl as {{ dbt.type_string() }}) as landl,
    cast(b.imkey as {{ dbt.type_string() }}) as imkey,
    cast(b.vbel2 as {{ dbt.type_string() }}) as vbel2,
    cast(b.vpos2 as {{ dbt.type_string() }}) as vpos2,
    cast(b.posn2 as {{ dbt.type_string() }}) as posn2,
    cast(b.eten2 as {{ dbt.type_string() }}) as eten2,
    cast(b.fistl as {{ dbt.type_string() }}) as fistl,
    cast(b.geber as {{ dbt.type_string() }}) as geber,
    cast(b.dabrz as {{ dbt.type_string() }}) as dabrz,
    cast(b.xnegp as {{ dbt.type_string() }}) as xnegp,
    cast(b.kostl as {{ dbt.type_string() }}) as kostl,
    cast(b.rfzei as {{ dbt.type_string() }}) as rfzei,
    cast(b.kkber as {{ dbt.type_string() }}) as kkber,
    cast(b.empfb as {{ dbt.type_string() }}) as empfb,
    cast(b.prctr as {{ dbt.type_string() }}) as prctr,
    cast(b.xref3 as {{ dbt.type_string() }}) as xref3,
    cast(b.qsskz as {{ dbt.type_string() }}) as qsskz,
    cast(b.zinkz as {{ dbt.type_string() }}) as zinkz,
    cast(b.dtws1 as {{ dbt.type_numeric() }}) as dtws1,
    cast(b.dtws2 as {{ dbt.type_numeric() }}) as dtws2,
    cast(b.dtws3 as {{ dbt.type_numeric() }}) as dtws3,
    cast(b.dtws4 as {{ dbt.type_numeric() }}) as dtws4,
    cast(b.xpypr as {{ dbt.type_string() }}) as xpypr,
    cast(b.kidno as {{ dbt.type_string() }}) as kidno,
    cast(b.absbt as {{ dbt.type_string() }}) as absbt,
    cast(b.ccbtc as {{ dbt.type_string() }}) as ccbtc,
    cast(b.pycur as {{ dbt.type_string() }}) as pycur,
    cast(b.pyamt as {{ dbt.type_numeric() }}) as pyamt,
    cast(b.bupla as {{ dbt.type_string() }}) as bupla,
    cast(b.secco as {{ dbt.type_string() }}) as secco,
    cast(b.cession_kz as {{ dbt.type_string() }}) as cession_kz,
    cast(b.ppdiff as {{ dbt.type_numeric() }}) as ppdiff,
    cast(b.ppdif2 as {{ dbt.type_numeric() }}) as ppdif2,
    cast(b.ppdif3 as {{ dbt.type_numeric() }}) as ppdif3,
    cast(b.kblnr as {{ dbt.type_string() }}) as kblnr,
    cast(b.kblpos as {{ dbt.type_string() }}) as kblpos,
    cast(b.grant_nbr as {{ dbt.type_string() }}) as grant_nbr,
    cast(b.gmvkz as {{ dbt.type_string() }}) as gmvkz,
    cast(b.srtype as {{ dbt.type_string() }}) as srtype,
    cast(b.lotkz as {{ dbt.type_string() }}) as lotkz,
    cast(b.fkber as {{ dbt.type_string() }}) as fkber,
    cast(b.intreno as {{ dbt.type_string() }}) as intreno,
    cast(b.pprct as {{ dbt.type_string() }}) as pprct,
    cast(b.buzid as {{ dbt.type_string() }}) as buzid,
    cast(b.auggj as {{ dbt.type_string() }}) as auggj,
    cast(b.hktid as {{ dbt.type_string() }}) as hktid,
    cast(b.budget_pd as {{ dbt.type_string() }}) as budget_pd,
    cast('' as {{ dbt.type_string() }}) as bdgt_account,
    cast('' as {{ dbt.type_string() }}) as re_account,
    cast(b.pays_prov as {{ dbt.type_string() }}) as pays_prov,
    cast(b.pays_tran as {{ dbt.type_string() }}) as pays_tran,
    cast(b.mndid as {{ dbt.type_string() }}) as mndid,
    cast('' as {{ dbt.type_string() }}) as payt_rsn,
    cast(b._dataaging as {{ dbt.type_string() }}) as _dataaging,
    cast('' as {{ dbt.type_string() }}) as kontt,
    cast('' as {{ dbt.type_string() }}) as kontl,
    cast('00000000' as {{ dbt.type_string() }}) as uebgdat,
    cast(b.vname as {{ dbt.type_string() }}) as vname,
    cast(b.egrup as {{ dbt.type_string() }}) as egrup,
    cast(b.btype as {{ dbt.type_string() }}) as btype,
    cast(b.propmano as {{ dbt.type_string() }}) as propmano,
    cast(b.gkont as {{ dbt.type_string() }}) as gkont,
    cast(b.gkart as {{ dbt.type_string() }}) as gkart,
    cast(b.ghkon as {{ dbt.type_string() }}) as ghkon,
    cast('' as {{ dbt.type_string() }}) as awtyp,
    cast('' as {{ dbt.type_string() }}) as logsystem_sender,
    cast('' as {{ dbt.type_string() }}) as bukrs_sender,
    cast('' as {{ dbt.type_string() }}) as belnr_sender,
    cast('0000' as {{ dbt.type_string() }}) as gjahr_sender,
    cast('000' as {{ dbt.type_string() }}) as buzei_sender,
    cast(0 as {{ dbt.type_int() }}) as pendays,
    cast('' as {{ dbt.type_string() }}) as j_1tpbupl
  from stg_sap__bsad_bck as b
  where b.xarch = 'X'
),

cleared_records as (
  select
    cast(i.mandt as {{ dbt.type_string() }}) as mandt,
    cast(i.bukrs as {{ dbt.type_string() }}) as bukrs,
    cast(i.kunnr as {{ dbt.type_string() }}) as kunnr,
    cast(i.umsks as {{ dbt.type_string() }}) as umsks,
    cast(i.umskz as {{ dbt.type_string() }}) as umskz,
    cast(i.augdt as {{ dbt.type_string() }}) as augdt,
    cast(i.augbl as {{ dbt.type_string() }}) as augbl,
    cast(i.zuonr as {{ dbt.type_string() }}) as zuonr,
    cast(i.gjahr as {{ dbt.type_string() }}) as gjahr,
    cast(i.belnr as {{ dbt.type_string() }}) as belnr,
    cast(i.buzei as {{ dbt.type_string() }}) as buzei,
    cast(h.budat as {{ dbt.type_string() }}) as budat,
    cast(h.bldat as {{ dbt.type_string() }}) as bldat,
    cast(h.cpudt as {{ dbt.type_string() }}) as cpudt,
    cast(h.waers as {{ dbt.type_string() }}) as waers,
    cast(h.xblnr as {{ dbt.type_string() }}) as xblnr,
    cast(h.blart as {{ dbt.type_string() }}) as blart,
    cast(h.monat as {{ dbt.type_string() }}) as monat,
    cast(i.bschl as {{ dbt.type_string() }}) as bschl,
    cast(i.zumsk as {{ dbt.type_string() }}) as zumsk,
    cast(i.shkzg as {{ dbt.type_string() }}) as shkzg,
    cast(i.gsber as {{ dbt.type_string() }}) as gsber,
    cast(i.tax_country as {{ dbt.type_string() }}) as tax_country,
    cast(i.mwskz as {{ dbt.type_string() }}) as mwskz,
    cast(i.txdat_from as {{ dbt.type_string() }}) as txdat_from,
    cast(i.dmbtr as {{ dbt.type_numeric() }}) as dmbtr,
    cast(i.wrbtr as {{ dbt.type_numeric() }}) as wrbtr,
    cast(i.fcsl as {{ dbt.type_numeric() }}) as fcsl,
    cast(i.rfccur as {{ dbt.type_string() }}) as rfccur,
    cast(i.mwsts as {{ dbt.type_numeric() }}) as mwsts,
    cast(i.wmwst as {{ dbt.type_numeric() }}) as wmwst,
    cast(i.lwsts as {{ dbt.type_numeric() }}) as lwsts,
    cast(i.bdiff as {{ dbt.type_numeric() }}) as bdiff,
    cast(i.bdif2 as {{ dbt.type_numeric() }}) as bdif2,
    cast(i.sgtxt as {{ dbt.type_string() }}) as sgtxt,
    cast(i.projn as {{ dbt.type_string() }}) as projn,
    cast(i.aufnr as {{ dbt.type_string() }}) as aufnr,
    cast(i.anln1 as {{ dbt.type_string() }}) as anln1,
    cast(i.anln2 as {{ dbt.type_string() }}) as anln2,
    cast(i.saknr as {{ dbt.type_string() }}) as saknr,
    cast(i.hkont as {{ dbt.type_string() }}) as hkont,
    cast(i.fkont as {{ dbt.type_string() }}) as fkont,
    cast(i.filkd as {{ dbt.type_string() }}) as filkd,
    cast(i.zfbdt as {{ dbt.type_string() }}) as zfbdt,
    cast(i.zterm as {{ dbt.type_string() }}) as zterm,
    cast(i.zbd1t as {{ dbt.type_numeric() }}) as zbd1t,
    cast(i.zbd2t as {{ dbt.type_numeric() }}) as zbd2t,
    cast(i.zbd3t as {{ dbt.type_numeric() }}) as zbd3t,
    cast(i.zbd1p as {{ dbt.type_numeric() }}) as zbd1p,
    cast(i.zbd2p as {{ dbt.type_numeric() }}) as zbd2p,
    cast(i.skfbt as {{ dbt.type_numeric() }}) as skfbt,
    cast(i.sknto as {{ dbt.type_numeric() }}) as sknto,
    cast(i.wskto as {{ dbt.type_numeric() }}) as wskto,
    cast(i.zlsch as {{ dbt.type_string() }}) as zlsch,
    cast(i.zlspr as {{ dbt.type_string() }}) as zlspr,
    cast(i.zbfix as {{ dbt.type_string() }}) as zbfix,
    cast(i.hbkid as {{ dbt.type_string() }}) as hbkid,
    cast(i.bvtyp as {{ dbt.type_string() }}) as bvtyp,
    cast(i.rebzg as {{ dbt.type_string() }}) as rebzg,
    cast(i.rebzj as {{ dbt.type_string() }}) as rebzj,
    cast(i.rebzz as {{ dbt.type_string() }}) as rebzz,
    cast(i.samnr as {{ dbt.type_string() }}) as samnr,
    cast(i.anfbn as {{ dbt.type_string() }}) as anfbn,
    cast(i.anfbj as {{ dbt.type_string() }}) as anfbj,
    cast(i.anfbu as {{ dbt.type_string() }}) as anfbu,
    cast(i.anfae as {{ dbt.type_string() }}) as anfae,
    cast(i.mansp as {{ dbt.type_string() }}) as mansp,
    cast(i.mschl as {{ dbt.type_string() }}) as mschl,
    cast(i.madat as {{ dbt.type_string() }}) as madat,
    cast(i.manst as {{ dbt.type_string() }}) as manst,
    cast(i.maber as {{ dbt.type_string() }}) as maber,
    cast(h.xnetb as {{ dbt.type_string() }}) as xnetb,
    cast(i.xanet as {{ dbt.type_string() }}) as xanet,
    cast(i.xcpdd as {{ dbt.type_string() }}) as xcpdd,
    cast(i.xinve as {{ dbt.type_string() }}) as xinve,
    cast(i.xzahl as {{ dbt.type_string() }}) as xzahl,
    cast(i.mwsk1 as {{ dbt.type_string() }}) as mwsk1,
    cast(i.txdat_from1 as {{ dbt.type_string() }}) as txdat_from1,
    cast(i.tax_country1 as {{ dbt.type_string() }}) as tax_country1,
    cast(i.dmbt1 as {{ dbt.type_numeric() }}) as dmbt1,
    cast(i.wrbt1 as {{ dbt.type_numeric() }}) as wrbt1,
    cast(i.hist_tax_factor1 as {{ dbt.type_string() }}) as hist_tax_factor1,
    cast(i.mwsk2 as {{ dbt.type_string() }}) as mwsk2,
    cast(i.txdat_from2 as {{ dbt.type_string() }}) as txdat_from2,
    cast(i.tax_country2 as {{ dbt.type_string() }}) as tax_country2,
    cast(i.dmbt2 as {{ dbt.type_numeric() }}) as dmbt2,
    cast(i.wrbt2 as {{ dbt.type_numeric() }}) as wrbt2,
    cast(i.hist_tax_factor2 as {{ dbt.type_string() }}) as hist_tax_factor2,
    cast(i.mwsk3 as {{ dbt.type_string() }}) as mwsk3,
    cast(i.txdat_from3 as {{ dbt.type_string() }}) as txdat_from3,
    cast(i.tax_country3 as {{ dbt.type_string() }}) as tax_country3,
    cast(i.dmbt3 as {{ dbt.type_numeric() }}) as dmbt3,
    cast(i.wrbt3 as {{ dbt.type_numeric() }}) as wrbt3,
    cast(i.hist_tax_factor3 as {{ dbt.type_string() }}) as hist_tax_factor3,
    cast(i.hist_tax_factor as {{ dbt.type_string() }}) as hist_tax_factor,
    cast(i.h_bstat as {{ dbt.type_string() }}) as bstat,
    cast(i.vbund as {{ dbt.type_string() }}) as vbund,
    cast(i.vbeln as {{ dbt.type_string() }}) as vbeln,
    cast(i.rebzt as {{ dbt.type_string() }}) as rebzt,
    cast('' as {{ dbt.type_string() }}) as infae,
    cast(i.stceg as {{ dbt.type_string() }}) as stceg,
    cast(i.egbld as {{ dbt.type_string() }}) as egbld,
    cast(i.eglld as {{ dbt.type_string() }}) as eglld,
    cast(i.rstgr as {{ dbt.type_string() }}) as rstgr,
    cast('' as {{ dbt.type_string() }}) as xnoza,
    cast(i.vertt as {{ dbt.type_string() }}) as vertt,
    cast(i.vertn as {{ dbt.type_string() }}) as vertn,
    cast(i.vbewa as {{ dbt.type_string() }}) as vbewa,
    cast(i.wverw as {{ dbt.type_string() }}) as wverw,
    cast(i.projk as {{ dbt.type_string() }}) as projk,
    cast(i.fipos as {{ dbt.type_string() }}) as fipos,
    cast(i.nplnr as {{ dbt.type_string() }}) as nplnr,
    cast(i.aufpl as {{ dbt.type_string() }}) as aufpl,
    cast(i.aplzl as {{ dbt.type_string() }}) as aplzl,
    cast(i.xegdr as {{ dbt.type_string() }}) as xegdr,
    cast(i.dmbe2 as {{ dbt.type_numeric() }}) as dmbe2,
    cast(i.dmbe3 as {{ dbt.type_numeric() }}) as dmbe3,
    cast(i.dmb21 as {{ dbt.type_numeric() }}) as dmb21,
    cast(i.dmb22 as {{ dbt.type_numeric() }}) as dmb22,
    cast(i.dmb23 as {{ dbt.type_numeric() }}) as dmb23,
    cast(i.dmb31 as {{ dbt.type_numeric() }}) as dmb31,
    cast(i.dmb32 as {{ dbt.type_numeric() }}) as dmb32,
    cast(i.dmb33 as {{ dbt.type_numeric() }}) as dmb33,
    cast(i.bdif3 as {{ dbt.type_numeric() }}) as bdif3,
    cast(i.xragl as {{ dbt.type_string() }}) as xragl,
    cast(i.uzawe as {{ dbt.type_string() }}) as uzawe,
    cast(h.xstov as {{ dbt.type_string() }}) as xstov,
    cast(i.mwst2 as {{ dbt.type_numeric() }}) as mwst2,
    cast(i.mwst3 as {{ dbt.type_numeric() }}) as mwst3,
    cast(i.sknt2 as {{ dbt.type_numeric() }}) as sknt2,
    cast(i.sknt3 as {{ dbt.type_numeric() }}) as sknt3,
    cast(i.xref1 as {{ dbt.type_string() }}) as xref1,
    cast(i.xref2 as {{ dbt.type_string() }}) as xref2,
    case
      when i._dataaging = '00000000' then cast('' as {{ dbt.type_string() }})
      else cast('X' as {{ dbt.type_string() }})
    end as xarch,
    cast(i.pswsl as {{ dbt.type_string() }}) as pswsl,
    cast(i.pswbt as {{ dbt.type_numeric() }}) as pswbt,
    cast(i.lzbkz as {{ dbt.type_string() }}) as lzbkz,
    cast(i.landl as {{ dbt.type_string() }}) as landl,
    cast(i.imkey as {{ dbt.type_string() }}) as imkey,
    cast(i.vbel2 as {{ dbt.type_string() }}) as vbel2,
    cast('000000' as {{ dbt.type_string() }}) as vpos2,
    cast(i.posn2 as {{ dbt.type_string() }}) as posn2,
    cast(i.eten2 as {{ dbt.type_string() }}) as eten2,
    cast(i.fistl as {{ dbt.type_string() }}) as fistl,
    cast(i.geber as {{ dbt.type_string() }}) as geber,
    cast(i.dabrz as {{ dbt.type_string() }}) as dabrz,
    cast(i.xnegp as {{ dbt.type_string() }}) as xnegp,
    cast(i.kostl as {{ dbt.type_string() }}) as kostl,
    cast(i.rfzei as {{ dbt.type_string() }}) as rfzei,
    cast(i.kkber as {{ dbt.type_string() }}) as kkber,
    cast(i.empfb as {{ dbt.type_string() }}) as empfb,
    cast(i.prctr as {{ dbt.type_string() }}) as prctr,
    cast(i.xref3 as {{ dbt.type_string() }}) as xref3,
    cast(i.qsskz as {{ dbt.type_string() }}) as qsskz,
    cast(i.zinkz as {{ dbt.type_string() }}) as zinkz,
    cast(i.dtws1 as {{ dbt.type_numeric() }}) as dtws1,
    cast(i.dtws2 as {{ dbt.type_numeric() }}) as dtws2,
    cast(i.dtws3 as {{ dbt.type_numeric() }}) as dtws3,
    cast(i.dtws4 as {{ dbt.type_numeric() }}) as dtws4,
    cast(i.xpypr as {{ dbt.type_string() }}) as xpypr,
    cast(i.kidno as {{ dbt.type_string() }}) as kidno,
    cast(i.absbt as {{ dbt.type_string() }}) as absbt,
    cast(i.ccbtc as {{ dbt.type_string() }}) as ccbtc,
    cast(i.pycur as {{ dbt.type_string() }}) as pycur,
    cast(i.pyamt as {{ dbt.type_numeric() }}) as pyamt,
    cast(i.bupla as {{ dbt.type_string() }}) as bupla,
    cast(i.secco as {{ dbt.type_string() }}) as secco,
    cast(i.cession_kz as {{ dbt.type_string() }}) as cession_kz,
    cast(i.ppdiff as {{ dbt.type_numeric() }}) as ppdiff,
    cast(i.ppdif2 as {{ dbt.type_numeric() }}) as ppdif2,
    cast(i.ppdif3 as {{ dbt.type_numeric() }}) as ppdif3,
    cast(i.kblnr as {{ dbt.type_string() }}) as kblnr,
    cast(i.kblpos as {{ dbt.type_string() }}) as kblpos,
    cast(i.grant_nbr as {{ dbt.type_string() }}) as grant_nbr,
    cast(i.gmvkz as {{ dbt.type_string() }}) as gmvkz,
    cast(i.srtype as {{ dbt.type_string() }}) as srtype,
    cast(h.lotkz as {{ dbt.type_string() }}) as lotkz,
    cast(case
      when i.fkber_long = '' then i.fkber
      else i.fkber_long
    end as {{ dbt.type_string() }}) as fkber,
    cast(i.intreno as {{ dbt.type_string() }}) as intreno,
    cast(i.pprct as {{ dbt.type_string() }}) as pprct,
    cast(i.buzid as {{ dbt.type_string() }}) as buzid,
    cast(i.auggj as {{ dbt.type_string() }}) as auggj,
    cast(i.hktid as {{ dbt.type_string() }}) as hktid,
    cast(i.budget_pd as {{ dbt.type_string() }}) as budget_pd,
    cast(i.bdgt_account as {{ dbt.type_string() }}) as bdgt_account,
    cast(i.re_account as {{ dbt.type_string() }}) as re_account,
    cast(i.pays_prov as {{ dbt.type_string() }}) as pays_prov,
    cast(i.pays_tran as {{ dbt.type_string() }}) as pays_tran,
    cast(i.mndid as {{ dbt.type_string() }}) as mndid,
    cast(i.payt_rsn as {{ dbt.type_string() }}) as payt_rsn,
    cast(i._dataaging as {{ dbt.type_string() }}) as _dataaging,
    cast(i.kontt as {{ dbt.type_string() }}) as kontt,
    cast(i.kontl as {{ dbt.type_string() }}) as kontl,
    cast('00000000' as {{ dbt.type_string() }}) as uebgdat,
    cast(i.vname as {{ dbt.type_string() }}) as vname,
    cast(i.egrup as {{ dbt.type_string() }}) as egrup,
    cast(i.btype as {{ dbt.type_string() }}) as btype,
    cast(h.propmano as {{ dbt.type_string() }}) as propmano,
    cast(i.gkont as {{ dbt.type_string() }}) as gkont,
    cast(i.gkart as {{ dbt.type_string() }}) as gkart,
    cast(i.ghkon as {{ dbt.type_string() }}) as ghkon,
    cast(h.awtyp as {{ dbt.type_string() }}) as awtyp,
    cast(h.logsystem_sender as {{ dbt.type_string() }}) as logsystem_sender,
    cast(h.bukrs_sender as {{ dbt.type_string() }}) as bukrs_sender,
    cast(h.belnr_sender as {{ dbt.type_string() }}) as belnr_sender,
    cast(h.gjahr_sender as {{ dbt.type_string() }}) as gjahr_sender,
    cast(i.buzei_sender as {{ dbt.type_string() }}) as buzei_sender,
    cast(i.pendays as {{ dbt.type_int() }}) as pendays,
    cast(i.j_1tpbupl as {{ dbt.type_string() }}) as j_1tpbupl
  from stg_sap__bseg as i
    left outer join stg_sap__bkpf as h
      on (h.mandt = i.mandt
          and h.bukrs = i.bukrs
          and h.gjahr = i.gjahr
          and h.belnr = i.belnr)
  where (i.koart = 'D'
    and not (i.augbl = '')
    and not (i.h_bstat = 'D')
    and not (i.h_bstat = 'M'))
)

select * 
from archived_records

union all

select * 
from cleared_records