{{ config(
    enabled=(var('sap_using_coep', True) and var('sap_using_acdoca', True) and var('sap_using_finsc_cmp_versnd', True) and var('sap_using_tka01', True) and var('sap_using_prps', True))
) }}

with coep_base as (

    select *
    from {{ ref('stg_sap__coep') }}

),

acdoca_processed as (

    select *
    from {{ ref('int_coep__original') }}

),

original_coep as (

    select
        cast(coep.mandt as {{ dbt.type_string() }}) as mandt,
        cast(coep.kokrs as {{ dbt.type_string() }}) as kokrs,
        cast(coep.belnr as {{ dbt.type_string() }}) as belnr,
        cast(coep.buzei as {{ dbt.type_string() }}) as buzei,
        cast(coep.perio as {{ dbt.type_string() }}) as perio,
        cast(coep.wtgbtr as {{ dbt.type_numeric() }}) as wtgbtr,
        cast(coep.wogbtr as {{ dbt.type_numeric() }}) as wogbtr,
        cast(coep.wkgbtr as {{ dbt.type_numeric() }}) as wkgbtr,
        cast(coep.wkfbtr as {{ dbt.type_numeric() }}) as wkfbtr,
        cast(coep.pagbtr as {{ dbt.type_numeric() }}) as pagbtr,
        cast(coep.pafbtr as {{ dbt.type_numeric() }}) as pafbtr,
        cast(coep.megbtr as {{ dbt.type_numeric() }}) as megbtr,
        cast(coep.mefbtr as {{ dbt.type_numeric() }}) as mefbtr,
        cast(coep.mbgbtr as {{ dbt.type_numeric() }}) as mbgbtr,
        cast(coep.mbfbtr as {{ dbt.type_numeric() }}) as mbfbtr,
        cast(coep.lednr as {{ dbt.type_string() }}) as lednr,
        cast(coep.objnr as {{ dbt.type_string() }}) as objnr,
        cast(coep.gjahr as {{ dbt.type_string() }}) as gjahr,
        cast(coep.wrttp as {{ dbt.type_string() }}) as wrttp,
        cast(coep.versn as {{ dbt.type_string() }}) as versn,
        cast(coep.kstar as {{ dbt.type_string() }}) as kstar,
        cast(coep.hrkft as {{ dbt.type_string() }}) as hrkft,
        cast(coep.vrgng as {{ dbt.type_string() }}) as vrgng,
        cast(coep.parob as {{ dbt.type_string() }}) as parob,
        cast(coep.parob1 as {{ dbt.type_string() }}) as parob1,
        cast(coep.uspob as {{ dbt.type_string() }}) as uspob,
        cast(coep.vbund as {{ dbt.type_string() }}) as vbund,
        cast(coep.pargb as {{ dbt.type_string() }}) as pargb,
        cast(coep.beknz as {{ dbt.type_string() }}) as beknz,
        cast(coep.twaer as {{ dbt.type_string() }}) as twaer,
        cast(coep.owaer as {{ dbt.type_string() }}) as owaer,
        cast(coep.meinh as {{ dbt.type_string() }}) as meinh,
        cast(coep.meinb as {{ dbt.type_string() }}) as meinb,
        cast(coep.mvflg as {{ dbt.type_string() }}) as mvflg,
        cast(coep.sgtxt as {{ dbt.type_string() }}) as sgtxt,
        cast(coep.refbz as {{ dbt.type_string() }}) as refbz,
        cast(coep.zlenr as {{ dbt.type_string() }}) as zlenr,
        cast(coep.bw_refbz as {{ dbt.type_string() }}) as bw_refbz,
        cast(coep.gkont as {{ dbt.type_string() }}) as gkont,
        cast(coep.gkoar as {{ dbt.type_string() }}) as gkoar,
        cast(coep.werks as {{ dbt.type_string() }}) as werks,
        cast(coep.matnr as {{ dbt.type_string() }}) as matnr,
        cast(coep.rbest as {{ dbt.type_numeric() }}) as rbest,
        cast(coep.ebeln as {{ dbt.type_string() }}) as ebeln,
        cast(coep.ebelp as {{ dbt.type_string() }}) as ebelp,
        cast(coep.zekkn as {{ dbt.type_string() }}) as zekkn,
        cast(coep.erlkz as {{ dbt.type_string() }}) as erlkz,
        cast(coep.pernr as {{ dbt.type_string() }}) as pernr,
        cast(coep.btrkl as {{ dbt.type_string() }}) as btrkl,
        rtrim(cast(coep.objnr_n1 as {{ dbt.type_string() }})) as objnr_n1,
        rtrim(cast(coep.objnr_n2 as {{ dbt.type_string() }})) as objnr_n2,
        rtrim(cast(coep.objnr_n3 as {{ dbt.type_string() }})) as objnr_n3,
        cast(coep.paobjnr as {{ dbt.type_string() }}) as paobjnr,
        cast(coep.beltp as {{ dbt.type_string() }}) as beltp,
        cast(coep.bukrs as {{ dbt.type_string() }}) as bukrs,
        cast(coep.gsber as {{ dbt.type_string() }}) as gsber,
        cast(coep.fkber as {{ dbt.type_string() }}) as fkber,
        cast(coep.scope as {{ dbt.type_string() }}) as scope,
        cast(coep.logsyso as {{ dbt.type_string() }}) as logsyso,
        cast(coep.pkstar as {{ dbt.type_string() }}) as pkstar,
        cast(coep.pbukrs as {{ dbt.type_string() }}) as pbukrs,
        cast(coep.pfkber as {{ dbt.type_string() }}) as pfkber,
        cast(coep.pscope as {{ dbt.type_string() }}) as pscope,
        cast(coep.logsysp as {{ dbt.type_string() }}) as logsysp,
        cast(coep.dabrz as {{ dbt.type_string() }}) as dabrz,
        cast(coep.bwstrat as {{ dbt.type_string() }}) as bwstrat,
        cast(coep.objnr_hk as {{ dbt.type_string() }}) as objnr_hk,
        cast(coep.timestmp as {{ dbt.type_string() }}) as timestmp,
        cast(coep.qmnum as {{ dbt.type_string() }}) as qmnum,
        cast(coep.geber as {{ dbt.type_string() }}) as geber,
        cast(coep.pgeber as {{ dbt.type_string() }}) as pgeber,
        cast(coep.grant_nbr as {{ dbt.type_string() }}) as grant_nbr,
        cast(coep.pgrant_nbr as {{ dbt.type_string() }}) as pgrant_nbr,
        cast(coep.refbz_fi as {{ dbt.type_string() }}) as refbz_fi,
        cast(coep.segment as {{ dbt.type_string() }}) as segment,
        cast(coep.psegment as {{ dbt.type_string() }}) as psegment,
        cast(coep.posnr as {{ dbt.type_string() }}) as posnr,
        cast(coep.prctr as {{ dbt.type_string() }}) as prctr,
        cast(coep.pprct as {{ dbt.type_string() }}) as pprct,
        cast(coep.budget_pd as {{ dbt.type_string() }}) as budget_pd,
        cast(coep.pbudget_pd as {{ dbt.type_string() }}) as pbudget_pd,
        cast(coep.prodper as {{ dbt.type_string() }}) as prodper,
        cast(coep.awtyp as {{ dbt.type_string() }}) as awtyp,
        rtrim(cast(coep.awkey as {{ dbt.type_string() }})) as awkey,
        cast(coep.awsys as {{ dbt.type_string() }}) as awsys,
        cast(coep.kwaer as {{ dbt.type_string() }}) as kwaer,
        cast(coep.accas as {{ dbt.type_string() }}) as accas,
        cast(coep.accasty as {{ dbt.type_string() }}) as accasty,
        cast(coep.kostl as {{ dbt.type_string() }}) as kostl,
        cast(coep.lstar as {{ dbt.type_string() }}) as lstar,
        cast(coep.aufnr as {{ dbt.type_string() }}) as aufnr,
        cast(coep.autyp as {{ dbt.type_string() }}) as autyp,
        cast(coep.pspnr as {{ dbt.type_string() }}) as pspnr,
        cast(coep.pspid as {{ dbt.type_string() }}) as pspid,
        cast(coep.vbeln as {{ dbt.type_string() }}) as vbeln,
        cast(coep.vbposnr as {{ dbt.type_string() }}) as vbposnr,
        cast(coep.ce4key as {{ dbt.type_string() }}) as ce4key,
        cast(coep.erkrs as {{ dbt.type_string() }}) as erkrs,
        cast(coep.paccas as {{ dbt.type_string() }}) as paccas,
        cast(coep.paccasty as {{ dbt.type_string() }}) as paccasty,
        cast(coep.pkostl as {{ dbt.type_string() }}) as pkostl,
        cast(coep.plstar as {{ dbt.type_string() }}) as plstar,
        cast(coep.paufnr as {{ dbt.type_string() }}) as paufnr,
        cast(coep.pautyp as {{ dbt.type_string() }}) as pautyp,
        cast(coep.ppspnr as {{ dbt.type_string() }}) as ppspnr,
        cast(coep.ppspid as {{ dbt.type_string() }}) as ppspid,
        cast(coep.pvbeln as {{ dbt.type_string() }}) as pvbeln,
        cast(coep.pvbposnr as {{ dbt.type_string() }}) as pvbposnr,
        cast(coep.pce4key as {{ dbt.type_string() }}) as pce4key,
        cast(coep.quant1 as {{ dbt.type_numeric() }}) as quant1,
        cast(coep.quant2 as {{ dbt.type_numeric() }}) as quant2,
        cast(coep.quant3 as {{ dbt.type_numeric() }}) as quant3,
        cast(coep.qunit1 as {{ dbt.type_string() }}) as qunit1,
        cast(coep.qunit2 as {{ dbt.type_string() }}) as qunit2,
        cast(coep.qunit3 as {{ dbt.type_string() }}) as qunit3

    from coep_base coep
    where not (cast(coep.wrttp as {{ dbt.type_string() }}) = '04' or cast(coep.wrttp as {{ dbt.type_string() }}) = 'U4' or cast(coep.wrttp as {{ dbt.type_string() }}) = 'U1')

),

derived_acdoca as (

    select
        cast(acdoca_processed.mandt as {{ dbt.type_string() }}) as mandt,
        cast(acdoca_processed.kokrs as {{ dbt.type_string() }}) as kokrs,
        cast(acdoca_processed.belnr as {{ dbt.type_string() }}) as belnr,
        cast(acdoca_processed.buzei as {{ dbt.type_string() }}) as buzei,
        cast(acdoca_processed.perio as {{ dbt.type_string() }}) as perio,
        cast(acdoca_processed.wtgbtr as {{ dbt.type_numeric() }}) as wtgbtr,
        cast(acdoca_processed.wogbtr as {{ dbt.type_numeric() }}) as wogbtr,
        cast(acdoca_processed.wkgbtr as {{ dbt.type_numeric() }}) as wkgbtr,
        cast(acdoca_processed.wkfbtr as {{ dbt.type_numeric() }}) as wkfbtr,
        cast(acdoca_processed.pagbtr as {{ dbt.type_numeric() }}) as pagbtr,
        cast(acdoca_processed.pafbtr as {{ dbt.type_numeric() }}) as pafbtr,
        cast(acdoca_processed.megbtr as {{ dbt.type_numeric() }}) as megbtr,
        cast(acdoca_processed.mefbtr as {{ dbt.type_numeric() }}) as mefbtr,
        cast(acdoca_processed.mbgbtr as {{ dbt.type_numeric() }}) as mbgbtr,
        cast(acdoca_processed.mbfbtr as {{ dbt.type_numeric() }}) as mbfbtr,
        cast(acdoca_processed.lednr as {{ dbt.type_string() }}) as lednr,
        cast(acdoca_processed.objnr as {{ dbt.type_string() }}) as objnr,
        cast(acdoca_processed.gjahr as {{ dbt.type_string() }}) as gjahr,
        cast('04' as {{ dbt.type_string() }}) as wrttp,
        cast(acdoca_processed.versn as {{ dbt.type_string() }}) as versn,
        cast(acdoca_processed.kstar as {{ dbt.type_string() }}) as kstar,
        cast(acdoca_processed.hrkft as {{ dbt.type_string() }}) as hrkft,
        cast(acdoca_processed.vrgng as {{ dbt.type_string() }}) as vrgng,
        cast(acdoca_processed.parob as {{ dbt.type_string() }}) as parob,
        cast(acdoca_processed.parob1 as {{ dbt.type_string() }}) as parob1,
        cast(acdoca_processed.uspob as {{ dbt.type_string() }}) as uspob,
        cast(acdoca_processed.vbund as {{ dbt.type_string() }}) as vbund,
        cast(acdoca_processed.pargb as {{ dbt.type_string() }}) as pargb,
        cast(acdoca_processed.beknz as {{ dbt.type_string() }}) as beknz,
        cast(acdoca_processed.twaer as {{ dbt.type_string() }}) as twaer,
        cast(acdoca_processed.owaer as {{ dbt.type_string() }}) as owaer,
        cast(acdoca_processed.meinh as {{ dbt.type_string() }}) as meinh,
        cast(acdoca_processed.meinb as {{ dbt.type_string() }}) as meinb,
        case
            when cast(acdoca_processed.mvflg as {{ dbt.type_string() }}) = '0' then cast('X' as {{ dbt.type_string() }})
            else cast('' as {{ dbt.type_string() }})
        end as mvflg,
        cast(acdoca_processed.sgtxt as {{ dbt.type_string() }}) as sgtxt,
        cast(acdoca_processed.refbz as {{ dbt.type_string() }}) as refbz,
        cast(acdoca_processed.zlenr as {{ dbt.type_string() }}) as zlenr,
        cast(acdoca_processed.bw_refbz as {{ dbt.type_string() }}) as bw_refbz,
        cast(acdoca_processed.gkont as {{ dbt.type_string() }}) as gkont,
        cast(acdoca_processed.gkoar as {{ dbt.type_string() }}) as gkoar,
        cast(acdoca_processed.werks as {{ dbt.type_string() }}) as werks,
        cast(acdoca_processed.matnr as {{ dbt.type_string() }}) as matnr,
        cast(acdoca_processed.rbest as {{ dbt.type_numeric() }}) as rbest,
        cast(acdoca_processed.ebeln as {{ dbt.type_string() }}) as ebeln,
        cast(acdoca_processed.ebelp as {{ dbt.type_string() }}) as ebelp,
        cast(acdoca_processed.zekkn as {{ dbt.type_string() }}) as zekkn,
        cast(acdoca_processed.erlkz as {{ dbt.type_string() }}) as erlkz,
        cast(acdoca_processed.pernr as {{ dbt.type_string() }}) as pernr,
        cast('00' as {{ dbt.type_string() }}) as btrkl,
        rtrim(cast(acdoca_processed.objnr_n1 as {{ dbt.type_string() }})) as objnr_n1,
        rtrim(cast(acdoca_processed.objnr_n2 as {{ dbt.type_string() }})) as objnr_n2,
        rtrim(cast(acdoca_processed.objnr_n3 as {{ dbt.type_string() }})) as objnr_n3,
        cast(acdoca_processed.paobjnr as {{ dbt.type_string() }}) as paobjnr,
        cast(acdoca_processed.beltp as {{ dbt.type_string() }}) as beltp,
        cast(acdoca_processed.bukrs as {{ dbt.type_string() }}) as bukrs,
        cast(acdoca_processed.gsber as {{ dbt.type_string() }}) as gsber,
        cast(acdoca_processed.fkber as {{ dbt.type_string() }}) as fkber,
        cast(acdoca_processed.scope as {{ dbt.type_string() }}) as scope,
        cast(acdoca_processed.logsyso as {{ dbt.type_string() }}) as logsyso,
        cast(acdoca_processed.pkstar as {{ dbt.type_string() }}) as pkstar,
        cast(acdoca_processed.pbukrs as {{ dbt.type_string() }}) as pbukrs,
        cast(acdoca_processed.pfkber as {{ dbt.type_string() }}) as pfkber,
        cast(acdoca_processed.pscope as {{ dbt.type_string() }}) as pscope,
        cast(acdoca_processed.logsysp as {{ dbt.type_string() }}) as logsysp,
        cast(acdoca_processed.dabrz as {{ dbt.type_string() }}) as dabrz,
        cast(acdoca_processed.bwstrat as {{ dbt.type_string() }}) as bwstrat,
        cast(acdoca_processed.objnr_hk as {{ dbt.type_string() }}) as objnr_hk,
        cast(acdoca_processed.timestmp as {{ dbt.type_string() }}) as timestmp,
        cast(acdoca_processed.qmnum as {{ dbt.type_string() }}) as qmnum,
        cast(acdoca_processed.geber as {{ dbt.type_string() }}) as geber,
        cast(acdoca_processed.pgeber as {{ dbt.type_string() }}) as pgeber,
        cast(acdoca_processed.grant_nbr as {{ dbt.type_string() }}) as grant_nbr,
        cast(acdoca_processed.pgrant_nbr as {{ dbt.type_string() }}) as pgrant_nbr,
        cast(acdoca_processed.refbz_fi as {{ dbt.type_string() }}) as refbz_fi,
        cast(acdoca_processed.segment as {{ dbt.type_string() }}) as segment,
        cast(acdoca_processed.psegment as {{ dbt.type_string() }}) as psegment,
        cast(acdoca_processed.posnr as {{ dbt.type_string() }}) as posnr,
        cast(acdoca_processed.prctr as {{ dbt.type_string() }}) as prctr,
        cast(acdoca_processed.pprct as {{ dbt.type_string() }}) as pprct,
        cast(acdoca_processed.budget_pd as {{ dbt.type_string() }}) as budget_pd,
        cast(acdoca_processed.pbudget_pd as {{ dbt.type_string() }}) as pbudget_pd,
        cast(acdoca_processed.prodper as {{ dbt.type_string() }}) as prodper,
        cast(acdoca_processed.awtyp as {{ dbt.type_string() }}) as awtyp,
        rtrim(cast(acdoca_processed.awkey as {{ dbt.type_string() }})) as awkey,
        cast(acdoca_processed.awsys as {{ dbt.type_string() }}) as awsys,
        cast(acdoca_processed.kwaer as {{ dbt.type_string() }}) as kwaer,
        cast(acdoca_processed.accas as {{ dbt.type_string() }}) as accas,
        cast(acdoca_processed.accasty as {{ dbt.type_string() }}) as accasty,
        cast(acdoca_processed.kostl as {{ dbt.type_string() }}) as kostl,
        cast(acdoca_processed.lstar as {{ dbt.type_string() }}) as lstar,
        cast(acdoca_processed.aufnr as {{ dbt.type_string() }}) as aufnr,
        cast(acdoca_processed.autyp as {{ dbt.type_string() }}) as autyp,
        cast(acdoca_processed.pspnr as {{ dbt.type_string() }}) as pspnr,
        cast(acdoca_processed.pspid as {{ dbt.type_string() }}) as pspid,
        cast(acdoca_processed.vbeln as {{ dbt.type_string() }}) as vbeln,
        cast(acdoca_processed.vbposnr as {{ dbt.type_string() }}) as vbposnr,
        cast(acdoca_processed.ce4key as {{ dbt.type_string() }}) as ce4key,
        cast(acdoca_processed.erkrs as {{ dbt.type_string() }}) as erkrs,
        cast(acdoca_processed.paccas as {{ dbt.type_string() }}) as paccas,
        cast(acdoca_processed.paccasty as {{ dbt.type_string() }}) as paccasty,
        cast(acdoca_processed.pkostl as {{ dbt.type_string() }}) as pkostl,
        cast(acdoca_processed.plstar as {{ dbt.type_string() }}) as plstar,
        cast(acdoca_processed.paufnr as {{ dbt.type_string() }}) as paufnr,
        cast(acdoca_processed.pautyp as {{ dbt.type_string() }}) as pautyp,
        cast(acdoca_processed.ppspnr as {{ dbt.type_string() }}) as ppspnr,
        cast(acdoca_processed.ppspid as {{ dbt.type_string() }}) as ppspid,
        cast(acdoca_processed.pvbeln as {{ dbt.type_string() }}) as pvbeln,
        cast(acdoca_processed.pvbposnr as {{ dbt.type_string() }}) as pvbposnr,
        cast(acdoca_processed.pce4key as {{ dbt.type_string() }}) as pce4key,
        cast(acdoca_processed.quant1 as {{ dbt.type_numeric() }}) as quant1,
        cast(acdoca_processed.quant2 as {{ dbt.type_numeric() }}) as quant2,
        cast(acdoca_processed.quant3 as {{ dbt.type_numeric() }}) as quant3,
        cast(acdoca_processed.qunit1 as {{ dbt.type_string() }}) as qunit1,
        cast(acdoca_processed.qunit2 as {{ dbt.type_string() }}) as qunit2,
        cast(acdoca_processed.qunit3 as {{ dbt.type_string() }}) as qunit3

    from acdoca_processed

),

final_union as (

    select * from original_coep
    union all
    select * from derived_acdoca

)

select * from final_union