{{
    config(
        enabled=var('sap_using_cosp_bak', True) and
                var('sap_using_acdoca', True) and
                var('sap_using_coep', True) and
                var('sap_using_finsc_cmp_versnd', True) and
                var('sap_using_tka01', True) and
                var('sap_using_t000', True) and
                var('sap_using_tj01', True) and
                var('sap_using_t006', True)
    )
}}

-- COSP compatibility view combining archived COSP_BAK data with derived ACDOCA data
-- This view replicates the SAP COSP table structure for cost object line items

with cosp_from_archive as (

    select
        cast(mandt as {{ dbt.type_string() }}) as mandt,
        cast('00' as {{ dbt.type_string() }}) as lednr,
        cast(objnr as {{ dbt.type_string() }}) as objnr,
        cast(gjahr as {{ dbt.type_string() }}) as gjahr,
        cast(wrttp as {{ dbt.type_string() }}) as wrttp,
        cast(versn as {{ dbt.type_string() }}) as versn,
        cast(kstar as {{ dbt.type_string() }}) as kstar,
        cast(hrkft as {{ dbt.type_string() }}) as hrkft,
        cast(vrgng as {{ dbt.type_string() }}) as vrgng,
        cast(vbund as {{ dbt.type_string() }}) as vbund,
        cast(pargb as {{ dbt.type_string() }}) as pargb,
        cast(beknz as {{ dbt.type_string() }}) as beknz,
        cast(twaer as {{ dbt.type_string() }}) as twaer,
        cast('016' as {{ dbt.type_string() }}) as perbl,
        cast(meinh as {{ dbt.type_string() }}) as meinh,
        cast(wtg001 as {{ dbt.type_numeric() }}) as wtg001,
        cast(wtg002 as {{ dbt.type_numeric() }}) as wtg002,
        cast(wtg003 as {{ dbt.type_numeric() }}) as wtg003,
        cast(wtg004 as {{ dbt.type_numeric() }}) as wtg004,
        cast(wtg005 as {{ dbt.type_numeric() }}) as wtg005,
        cast(wtg006 as {{ dbt.type_numeric() }}) as wtg006,
        cast(wtg007 as {{ dbt.type_numeric() }}) as wtg007,
        cast(wtg008 as {{ dbt.type_numeric() }}) as wtg008,
        cast(wtg009 as {{ dbt.type_numeric() }}) as wtg009,
        cast(wtg010 as {{ dbt.type_numeric() }}) as wtg010,
        cast(wtg011 as {{ dbt.type_numeric() }}) as wtg011,
        cast(wtg012 as {{ dbt.type_numeric() }}) as wtg012,
        cast(wtg013 as {{ dbt.type_numeric() }}) as wtg013,
        cast(wtg014 as {{ dbt.type_numeric() }}) as wtg014,
        cast(wtg015 as {{ dbt.type_numeric() }}) as wtg015,
        cast(wtg016 as {{ dbt.type_numeric() }}) as wtg016,
        cast(wog001 as {{ dbt.type_numeric() }}) as wog001,
        cast(wog002 as {{ dbt.type_numeric() }}) as wog002,
        cast(wog003 as {{ dbt.type_numeric() }}) as wog003,
        cast(wog004 as {{ dbt.type_numeric() }}) as wog004,
        cast(wog005 as {{ dbt.type_numeric() }}) as wog005,
        cast(wog006 as {{ dbt.type_numeric() }}) as wog006,
        cast(wog007 as {{ dbt.type_numeric() }}) as wog007,
        cast(wog008 as {{ dbt.type_numeric() }}) as wog008,
        cast(wog009 as {{ dbt.type_numeric() }}) as wog009,
        cast(wog010 as {{ dbt.type_numeric() }}) as wog010,
        cast(wog011 as {{ dbt.type_numeric() }}) as wog011,
        cast(wog012 as {{ dbt.type_numeric() }}) as wog012,
        cast(wog013 as {{ dbt.type_numeric() }}) as wog013,
        cast(wog014 as {{ dbt.type_numeric() }}) as wog014,
        cast(wog015 as {{ dbt.type_numeric() }}) as wog015,
        cast(wog016 as {{ dbt.type_numeric() }}) as wog016,
        cast(wkg001 as {{ dbt.type_numeric() }}) as wkg001,
        cast(wkg002 as {{ dbt.type_numeric() }}) as wkg002,
        cast(wkg003 as {{ dbt.type_numeric() }}) as wkg003,
        cast(wkg004 as {{ dbt.type_numeric() }}) as wkg004,
        cast(wkg005 as {{ dbt.type_numeric() }}) as wkg005,
        cast(wkg006 as {{ dbt.type_numeric() }}) as wkg006,
        cast(wkg007 as {{ dbt.type_numeric() }}) as wkg007,
        cast(wkg008 as {{ dbt.type_numeric() }}) as wkg008,
        cast(wkg009 as {{ dbt.type_numeric() }}) as wkg009,
        cast(wkg010 as {{ dbt.type_numeric() }}) as wkg010,
        cast(wkg011 as {{ dbt.type_numeric() }}) as wkg011,
        cast(wkg012 as {{ dbt.type_numeric() }}) as wkg012,
        cast(wkg013 as {{ dbt.type_numeric() }}) as wkg013,
        cast(wkg014 as {{ dbt.type_numeric() }}) as wkg014,
        cast(wkg015 as {{ dbt.type_numeric() }}) as wkg015,
        cast(wkg016 as {{ dbt.type_numeric() }}) as wkg016,
        cast(wkf001 as {{ dbt.type_numeric() }}) as wkf001,
        cast(wkf002 as {{ dbt.type_numeric() }}) as wkf002,
        cast(wkf003 as {{ dbt.type_numeric() }}) as wkf003,
        cast(wkf004 as {{ dbt.type_numeric() }}) as wkf004,
        cast(wkf005 as {{ dbt.type_numeric() }}) as wkf005,
        cast(wkf006 as {{ dbt.type_numeric() }}) as wkf006,
        cast(wkf007 as {{ dbt.type_numeric() }}) as wkf007,
        cast(wkf008 as {{ dbt.type_numeric() }}) as wkf008,
        cast(wkf009 as {{ dbt.type_numeric() }}) as wkf009,
        cast(wkf010 as {{ dbt.type_numeric() }}) as wkf010,
        cast(wkf011 as {{ dbt.type_numeric() }}) as wkf011,
        cast(wkf012 as {{ dbt.type_numeric() }}) as wkf012,
        cast(wkf013 as {{ dbt.type_numeric() }}) as wkf013,
        cast(wkf014 as {{ dbt.type_numeric() }}) as wkf014,
        cast(wkf015 as {{ dbt.type_numeric() }}) as wkf015,
        cast(wkf016 as {{ dbt.type_numeric() }}) as wkf016,
        cast(pag001 as {{ dbt.type_numeric() }}) as pag001,
        cast(pag002 as {{ dbt.type_numeric() }}) as pag002,
        cast(pag003 as {{ dbt.type_numeric() }}) as pag003,
        cast(pag004 as {{ dbt.type_numeric() }}) as pag004,
        cast(pag005 as {{ dbt.type_numeric() }}) as pag005,
        cast(pag006 as {{ dbt.type_numeric() }}) as pag006,
        cast(pag007 as {{ dbt.type_numeric() }}) as pag007,
        cast(pag008 as {{ dbt.type_numeric() }}) as pag008,
        cast(pag009 as {{ dbt.type_numeric() }}) as pag009,
        cast(pag010 as {{ dbt.type_numeric() }}) as pag010,
        cast(pag011 as {{ dbt.type_numeric() }}) as pag011,
        cast(pag012 as {{ dbt.type_numeric() }}) as pag012,
        cast(pag013 as {{ dbt.type_numeric() }}) as pag013,
        cast(pag014 as {{ dbt.type_numeric() }}) as pag014,
        cast(pag015 as {{ dbt.type_numeric() }}) as pag015,
        cast(pag016 as {{ dbt.type_numeric() }}) as pag016,
        cast(meg001 as {{ dbt.type_numeric() }}) as meg001,
        cast(meg002 as {{ dbt.type_numeric() }}) as meg002,
        cast(meg003 as {{ dbt.type_numeric() }}) as meg003,
        cast(meg004 as {{ dbt.type_numeric() }}) as meg004,
        cast(meg005 as {{ dbt.type_numeric() }}) as meg005,
        cast(meg006 as {{ dbt.type_numeric() }}) as meg006,
        cast(meg007 as {{ dbt.type_numeric() }}) as meg007,
        cast(meg008 as {{ dbt.type_numeric() }}) as meg008,
        cast(meg009 as {{ dbt.type_numeric() }}) as meg009,
        cast(meg010 as {{ dbt.type_numeric() }}) as meg010,
        cast(meg011 as {{ dbt.type_numeric() }}) as meg011,
        cast(meg012 as {{ dbt.type_numeric() }}) as meg012,
        cast(meg013 as {{ dbt.type_numeric() }}) as meg013,
        cast(meg014 as {{ dbt.type_numeric() }}) as meg014,
        cast(meg015 as {{ dbt.type_numeric() }}) as meg015,
        cast(meg016 as {{ dbt.type_numeric() }}) as meg016,
        cast(mef001 as {{ dbt.type_numeric() }}) as mef001,
        cast(mef002 as {{ dbt.type_numeric() }}) as mef002,
        cast(mef003 as {{ dbt.type_numeric() }}) as mef003,
        cast(mef004 as {{ dbt.type_numeric() }}) as mef004,
        cast(mef005 as {{ dbt.type_numeric() }}) as mef005,
        cast(mef006 as {{ dbt.type_numeric() }}) as mef006,
        cast(mef007 as {{ dbt.type_numeric() }}) as mef007,
        cast(mef008 as {{ dbt.type_numeric() }}) as mef008,
        cast(mef009 as {{ dbt.type_numeric() }}) as mef009,
        cast(mef010 as {{ dbt.type_numeric() }}) as mef010,
        cast(mef011 as {{ dbt.type_numeric() }}) as mef011,
        cast(mef012 as {{ dbt.type_numeric() }}) as mef012,
        cast(mef013 as {{ dbt.type_numeric() }}) as mef013,
        cast(mef014 as {{ dbt.type_numeric() }}) as mef014,
        cast(mef015 as {{ dbt.type_numeric() }}) as mef015,
        cast(mef016 as {{ dbt.type_numeric() }}) as mef016,
        cast(muv001 as {{ dbt.type_string() }}) as muv001,
        cast(muv002 as {{ dbt.type_string() }}) as muv002,
        cast(muv003 as {{ dbt.type_string() }}) as muv003,
        cast(muv004 as {{ dbt.type_string() }}) as muv004,
        cast(muv005 as {{ dbt.type_string() }}) as muv005,
        cast(muv006 as {{ dbt.type_string() }}) as muv006,
        cast(muv007 as {{ dbt.type_string() }}) as muv007,
        cast(muv008 as {{ dbt.type_string() }}) as muv008,
        cast(muv009 as {{ dbt.type_string() }}) as muv009,
        cast(muv010 as {{ dbt.type_string() }}) as muv010,
        cast(muv011 as {{ dbt.type_string() }}) as muv011,
        cast(muv012 as {{ dbt.type_string() }}) as muv012,
        cast(muv013 as {{ dbt.type_string() }}) as muv013,
        cast(muv014 as {{ dbt.type_string() }}) as muv014,
        cast(muv015 as {{ dbt.type_string() }}) as muv015,
        cast(muv016 as {{ dbt.type_string() }}) as muv016,
        cast(beltp as {{ dbt.type_string() }}) as beltp,
        cast(timestmp as {{ dbt.type_string() }}) as timestmp,
        cast(bukrs as {{ dbt.type_string() }}) as bukrs,
        cast(fkber as {{ dbt.type_string() }}) as fkber,
        cast(segment as {{ dbt.type_string() }}) as segment,
        cast(geber as {{ dbt.type_string() }}) as geber,
        cast(grant_nbr as {{ dbt.type_string() }}) as grant_nbr,
        cast(budget_pd as {{ dbt.type_string() }}) as budget_pd

    from {{ ref('stg_sap__cosp_bak') }}
    where not (cast(wrttp as {{ dbt.type_string() }}) = '04' or cast(wrttp as {{ dbt.type_string() }}) = '11')

),

cosp_from_acdoca_aggregated as (

    select
        cast(mandt as {{ dbt.type_string() }}) as mandt,
        cast('00' as {{ dbt.type_string() }}) as lednr,
        cast(objnr as {{ dbt.type_string() }}) as objnr,
        cast(gjahr as {{ dbt.type_string() }}) as gjahr,
        cast(wrttp as {{ dbt.type_string() }}) as wrttp,
        cast(versn as {{ dbt.type_string() }}) as versn,
        cast(kstar as {{ dbt.type_string() }}) as kstar,
        cast(hrkft as {{ dbt.type_string() }}) as hrkft,
        cast(vrgng as {{ dbt.type_string() }}) as vrgng,
        cast(vbund as {{ dbt.type_string() }}) as vbund,
        cast(pargb as {{ dbt.type_string() }}) as pargb,
        cast(beknz as {{ dbt.type_string() }}) as beknz,
        cast(twaer as {{ dbt.type_string() }}) as twaer,
        cast('016' as {{ dbt.type_string() }}) as perbl,
        cast(meinh as {{ dbt.type_string() }}) as meinh,
        cast(beltp as {{ dbt.type_string() }}) as beltp,
        cast(bukrs as {{ dbt.type_string() }}) as bukrs,
        cast(fkber as {{ dbt.type_string() }}) as fkber,
        cast(segment as {{ dbt.type_string() }}) as segment,
        cast(geber as {{ dbt.type_string() }}) as geber,
        cast(grant_nbr as {{ dbt.type_string() }}) as grant_nbr,
        cast(budget_pd as {{ dbt.type_string() }}) as budget_pd,
        -- Period-based transaction currency amounts
        sum(case when cast(perio as {{ dbt.type_string() }}) = '001' then wtgbtr else 0 end) as wtg001,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '002' then wtgbtr else 0 end) as wtg002,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '003' then wtgbtr else 0 end) as wtg003,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '004' then wtgbtr else 0 end) as wtg004,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '005' then wtgbtr else 0 end) as wtg005,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '006' then wtgbtr else 0 end) as wtg006,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '007' then wtgbtr else 0 end) as wtg007,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '008' then wtgbtr else 0 end) as wtg008,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '009' then wtgbtr else 0 end) as wtg009,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '010' then wtgbtr else 0 end) as wtg010,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '011' then wtgbtr else 0 end) as wtg011,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '012' then wtgbtr else 0 end) as wtg012,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '013' then wtgbtr else 0 end) as wtg013,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '014' then wtgbtr else 0 end) as wtg014,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '015' then wtgbtr else 0 end) as wtg015,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '016' then wtgbtr else 0 end) as wtg016,
        -- Period-based object currency amounts
        sum(case when cast(perio as {{ dbt.type_string() }}) = '001' then wogbtr else 0 end) as wog001,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '002' then wogbtr else 0 end) as wog002,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '003' then wogbtr else 0 end) as wog003,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '004' then wogbtr else 0 end) as wog004,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '005' then wogbtr else 0 end) as wog005,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '006' then wogbtr else 0 end) as wog006,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '007' then wogbtr else 0 end) as wog007,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '008' then wogbtr else 0 end) as wog008,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '009' then wogbtr else 0 end) as wog009,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '010' then wogbtr else 0 end) as wog010,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '011' then wogbtr else 0 end) as wog011,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '012' then wogbtr else 0 end) as wog012,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '013' then wogbtr else 0 end) as wog013,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '014' then wogbtr else 0 end) as wog014,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '015' then wogbtr else 0 end) as wog015,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '016' then wogbtr else 0 end) as wog016,
        -- Period-based controlling currency amounts
        sum(case when cast(perio as {{ dbt.type_string() }}) = '001' then wkgbtr else 0 end) as wkg001,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '002' then wkgbtr else 0 end) as wkg002,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '003' then wkgbtr else 0 end) as wkg003,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '004' then wkgbtr else 0 end) as wkg004,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '005' then wkgbtr else 0 end) as wkg005,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '006' then wkgbtr else 0 end) as wkg006,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '007' then wkgbtr else 0 end) as wkg007,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '008' then wkgbtr else 0 end) as wkg008,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '009' then wkgbtr else 0 end) as wkg009,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '010' then wkgbtr else 0 end) as wkg010,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '011' then wkgbtr else 0 end) as wkg011,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '012' then wkgbtr else 0 end) as wkg012,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '013' then wkgbtr else 0 end) as wkg013,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '014' then wkgbtr else 0 end) as wkg014,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '015' then wkgbtr else 0 end) as wkg015,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '016' then wkgbtr else 0 end) as wkg016,
        -- Period-based fixed currency amounts
        sum(case when cast(perio as {{ dbt.type_string() }}) = '001' then wkfbtr else 0 end) as wkf001,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '002' then wkfbtr else 0 end) as wkf002,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '003' then wkfbtr else 0 end) as wkf003,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '004' then wkfbtr else 0 end) as wkf004,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '005' then wkfbtr else 0 end) as wkf005,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '006' then wkfbtr else 0 end) as wkf006,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '007' then wkfbtr else 0 end) as wkf007,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '008' then wkfbtr else 0 end) as wkf008,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '009' then wkfbtr else 0 end) as wkf009,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '010' then wkfbtr else 0 end) as wkf010,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '011' then wkfbtr else 0 end) as wkf011,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '012' then wkfbtr else 0 end) as wkf012,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '013' then wkfbtr else 0 end) as wkf013,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '014' then wkfbtr else 0 end) as wkf014,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '015' then wkfbtr else 0 end) as wkf015,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '016' then wkfbtr else 0 end) as wkf016,
        -- Period-based plan amounts
        sum(case when cast(perio as {{ dbt.type_string() }}) = '001' then pagbtr else 0 end) as pag001,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '002' then pagbtr else 0 end) as pag002,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '003' then pagbtr else 0 end) as pag003,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '004' then pagbtr else 0 end) as pag004,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '005' then pagbtr else 0 end) as pag005,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '006' then pagbtr else 0 end) as pag006,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '007' then pagbtr else 0 end) as pag007,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '008' then pagbtr else 0 end) as pag008,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '009' then pagbtr else 0 end) as pag009,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '010' then pagbtr else 0 end) as pag010,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '011' then pagbtr else 0 end) as pag011,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '012' then pagbtr else 0 end) as pag012,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '013' then pagbtr else 0 end) as pag013,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '014' then pagbtr else 0 end) as pag014,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '015' then pagbtr else 0 end) as pag015,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '016' then pagbtr else 0 end) as pag016,
        -- Period-based quantity amounts
        sum(case when cast(perio as {{ dbt.type_string() }}) = '001' then megbtr else 0 end) as meg001,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '002' then megbtr else 0 end) as meg002,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '003' then megbtr else 0 end) as meg003,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '004' then megbtr else 0 end) as meg004,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '005' then megbtr else 0 end) as meg005,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '006' then megbtr else 0 end) as meg006,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '007' then megbtr else 0 end) as meg007,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '008' then megbtr else 0 end) as meg008,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '009' then megbtr else 0 end) as meg009,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '010' then megbtr else 0 end) as meg010,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '011' then megbtr else 0 end) as meg011,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '012' then megbtr else 0 end) as meg012,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '013' then megbtr else 0 end) as meg013,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '014' then megbtr else 0 end) as meg014,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '015' then megbtr else 0 end) as meg015,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '016' then megbtr else 0 end) as meg016,
        -- Period-based fixed quantity amounts
        sum(case when cast(perio as {{ dbt.type_string() }}) = '001' then mefbtr else 0 end) as mef001,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '002' then mefbtr else 0 end) as mef002,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '003' then mefbtr else 0 end) as mef003,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '004' then mefbtr else 0 end) as mef004,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '005' then mefbtr else 0 end) as mef005,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '006' then mefbtr else 0 end) as mef006,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '007' then mefbtr else 0 end) as mef007,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '008' then mefbtr else 0 end) as mef008,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '009' then mefbtr else 0 end) as mef009,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '010' then mefbtr else 0 end) as mef010,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '011' then mefbtr else 0 end) as mef011,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '012' then mefbtr else 0 end) as mef012,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '013' then mefbtr else 0 end) as mef013,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '014' then mefbtr else 0 end) as mef014,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '015' then mefbtr else 0 end) as mef015,
        sum(case when cast(perio as {{ dbt.type_string() }}) = '016' then mefbtr else 0 end) as mef016,
        -- Period-based manual update flags
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '001' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv001,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '002' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv002,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '003' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv003,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '004' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv004,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '005' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv005,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '006' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv006,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '007' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv007,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '008' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv008,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '009' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv009,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '010' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv010,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '011' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv011,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '012' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv012,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '013' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv013,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '014' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv014,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '015' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv015,
        case when max(case when cast(perio as {{ dbt.type_string() }}) = '016' then muvflg else 0 end) = 1 then cast('X' as {{ dbt.type_string() }}) else cast('' as {{ dbt.type_string() }}) end as muv016,
        cast(max(timestmp) as {{ dbt.type_string() }}) as timestmp

    from {{ ref('int_cosp__acdoca_derived') }}
    where cast(wrttp as {{ dbt.type_string() }}) in ('04', '11')
    {{ dbt_utils.group_by(n=22) }}

),

cosp_from_acdoca as (

    select
        mandt,
        lednr,
        objnr,
        gjahr,
        wrttp,
        versn,
        kstar,
        hrkft,
        vrgng,
        vbund,
        pargb,
        beknz,
        twaer,
        perbl,
        meinh,
        wtg001,
        wtg002,
        wtg003,
        wtg004,
        wtg005,
        wtg006,
        wtg007,
        wtg008,
        wtg009,
        wtg010,
        wtg011,
        wtg012,
        wtg013,
        wtg014,
        wtg015,
        wtg016,
        wog001,
        wog002,
        wog003,
        wog004,
        wog005,
        wog006,
        wog007,
        wog008,
        wog009,
        wog010,
        wog011,
        wog012,
        wog013,
        wog014,
        wog015,
        wog016,
        wkg001,
        wkg002,
        wkg003,
        wkg004,
        wkg005,
        wkg006,
        wkg007,
        wkg008,
        wkg009,
        wkg010,
        wkg011,
        wkg012,
        wkg013,
        wkg014,
        wkg015,
        wkg016,
        wkf001,
        wkf002,
        wkf003,
        wkf004,
        wkf005,
        wkf006,
        wkf007,
        wkf008,
        wkf009,
        wkf010,
        wkf011,
        wkf012,
        wkf013,
        wkf014,
        wkf015,
        wkf016,
        pag001,
        pag002,
        pag003,
        pag004,
        pag005,
        pag006,
        pag007,
        pag008,
        pag009,
        pag010,
        pag011,
        pag012,
        pag013,
        pag014,
        pag015,
        pag016,
        meg001,
        meg002,
        meg003,
        meg004,
        meg005,
        meg006,
        meg007,
        meg008,
        meg009,
        meg010,
        meg011,
        meg012,
        meg013,
        meg014,
        meg015,
        meg016,
        mef001,
        mef002,
        mef003,
        mef004,
        mef005,
        mef006,
        mef007,
        mef008,
        mef009,
        mef010,
        mef011,
        mef012,
        mef013,
        mef014,
        mef015,
        mef016,
        muv001,
        muv002,
        muv003,
        muv004,
        muv005,
        muv006,
        muv007,
        muv008,
        muv009,
        muv010,
        muv011,
        muv012,
        muv013,
        muv014,
        muv015,
        muv016,
        beltp,
        timestmp,
        bukrs,
        fkber,
        segment,
        geber,
        grant_nbr,
        budget_pd

    from cosp_from_acdoca_aggregated

)

select * from cosp_from_archive
union all
select * from cosp_from_acdoca