SELECT
A.RCLNT,
A.RYEAR,
A.BELNR AS DOCNR,
LR.RLDNR AS RLDNR,
A.RBUKRS,
A.DOCLN,
(A.BTTYPE) AS ACTIV,
A.RMVCT,
A.RTCUR,
A.RUNIT,
A.AWTYP,
A.RRCTY,
'001' AS RVERS,
A.AWSYS AS LOGSYS,
A.RACCT,
CASE WHEN NOT ( A.CO_BUZEI = '000' ) 
THEN A.RACCT 
ELSE '' 
END AS COST_ELEM,
A.RCNTR,
A.PRCTR,
A.RFAREA,
A.RBUSA,
A.KOKRS,
A.SEGMENT,
A.SCNTR,
A.PPRCTR,
A.SFAREA,
A.SBUSA,
A.RASSC,
A.PSEGMENT,
A.TSL,
A.HSL,
CASE WHEN LC.CURPOSK = '2' 
THEN A.KSL WHEN LC.CURPOSO = '2' 
THEN A.OSL WHEN LC.CURPOSV = '2' 
THEN A.VSL WHEN LC.CURPOSB = '2' 
THEN A.BSL WHEN LC.CURPOSC = '2' 
THEN A.CSL WHEN LC.CURPOSD = '2' 
THEN A.DSL WHEN LC.CURPOSE = '2' 
THEN A.ESL WHEN LC.CURPOSF = '2' 
THEN A.FSL WHEN LC.CURPOSG = '2' 
THEN A.GSL 
ELSE CAST( 0 AS DECIMAL( 000023,
000000)) 
END AS KSL,
CASE WHEN LC.CURPOSO = '3' 
THEN A.OSL WHEN LC.CURPOSK = '3' 
THEN A.KSL WHEN LC.CURPOSV = '3' 
THEN A.VSL WHEN LC.CURPOSB = '3' 
THEN A.BSL WHEN LC.CURPOSC = '3' 
THEN A.CSL WHEN LC.CURPOSD = '3' 
THEN A.DSL WHEN LC.CURPOSE = '3' 
THEN A.ESL WHEN LC.CURPOSF = '3' 
THEN A.FSL WHEN LC.CURPOSG = '3' 
THEN A.GSL 
ELSE CAST( 0 AS DECIMAL( 000023,000000)) 	END AS OSL,
A.MSL,
A.WSL,
A.FSL,
A.VSL,
A.DRCRK,
A.POPER,
A.RWCUR,
A.GJAHR,
A.BUDAT,
A.BELNR,
A.BUZEI,
A.BSCHL,
A.BSTAT,
A.LINETYPE,
A.XSPLITMOD,
A.USNAM,
A.TIMESTAMP,
A._DATAAGING,
A.FIKRS,
A.RFUND,
A.RGRANT_NBR,
A.RBUDGET_PD,
A.SFUND,
A.SGRANT_NBR,
A.SBUDGET_PD,
A.RE_BUKRS,
A.RE_ACCOUNT,
A.VNAME,
A.EGRUP,
A.RECID,
A.MIG_SOURCE,
A.MIG_DOCLN,
A.RHCUR,
A.RFCUR,
A.RVCUR,
A.FCSL,
A.RFCCUR,
CASE WHEN LC.CURPOSK = '2' 
THEN A.RKCUR WHEN LC.CURPOSO = '2' 
THEN A.ROCUR WHEN LC.CURPOSV = '2' 
THEN A.RVCUR 
ELSE '' 
END AS RKCUR,
CASE WHEN LC.CURPOSO = '3' 
THEN A.ROCUR WHEN LC.CURPOSK = '3' 
THEN A.RKCUR WHEN LC.CURPOSV = '3' 
THEN A.RVCUR 
ELSE '' 
END AS ROCUR 
FROM {{ source('raw_tables', 'acdoca') }} A 
INNER JOIN {{ source('raw_tables', 'finsc_ledger_rep') }} LR 
    ON ( LR.MANDT = A.RCLNT 
    AND LR.RLDNR_PERS = A.RLDNR 
    AND A.RCLNT = LR.MANDT )
INNER JOIN {{ source('raw_tables', 'finsc_ld_cmp') }} LC 
    ON ( LC.MANDT = A.RCLNT 
    AND LC.BUKRS = A.RBUKRS 
    AND LC.RLDNR = LR.RLDNR 
    AND A.RCLNT = LC.MANDT )
where ( A.BSTAT = '' 
    OR A.BSTAT = 'L' 
    OR A.BSTAT = 'U' 
    OR A.BSTAT = 'J' 
    OR A.BSTAT = 'T' 
    OR ( A.BSTAT = 'C' 
        AND A.POPER = '000' ) )
