with NSDM_V_MARC_AGG AS	(
SELECT	
MATDOC_EXTRACT.MANDT,	
MATDOC_EXTRACT.MATBF AS MATNR,	
MATDOC_EXTRACT.WERKS,	
MATDOC_EXTRACT.LBBSA_SID AS LBBSA,	
SUM( MATDOC_EXTRACT.STOCK_QTY_L2 ) AS STOCK_QTY,	
SUM( MATDOC_EXTRACT._CWM_STOCK_QTY_L2 ) AS _CWM_STOCK_QTY,	
SUM( MATDOC_EXTRACT.STOCK_VKWRT_L2 ) AS STOCK_VKWRT,	
MAX( MATDOC_EXTRACT.GJPER_CURR_PER ) AS GJPER_MAX	
FROM {{ source('raw_tables', 'matdoc_extract') }} MATDOC_EXTRACT	
WHERE	
( MATDOC_EXTRACT.STOCK_IND_L2 = ''	
AND ( MATDOC_EXTRACT.SOBKZ = ''	
AND ( MATDOC_EXTRACT.LBBSA_SID = '05'	
OR MATDOC_EXTRACT.LBBSA_SID = '06'	
OR MATDOC_EXTRACT.LBBSA_SID = '09'	
OR MATDOC_EXTRACT.LBBSA_SID = '10' ) ) )	
GROUP BY MATDOC_EXTRACT.MANDT,	
MATDOC_EXTRACT.MATBF,	
MATDOC_EXTRACT.WERKS,	
MATDOC_EXTRACT.LBBSA_SID	
)
,

NSDM_V_MARC_DIFF AS	(
SELECT	
NSDM_V_MARC_AGG.MANDT,	
NSDM_V_MARC_AGG.MATNR,	
NSDM_V_MARC_AGG.WERKS,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '05' THEN NSDM_V_MARC_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS UMLMC,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '06' THEN NSDM_V_MARC_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS TRAME,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '05' THEN NSDM_V_MARC_AGG.STOCK_VKWRT	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS VKUMC,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '06' THEN NSDM_V_MARC_AGG.STOCK_VKWRT	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS VKTRW,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '09' THEN NSDM_V_MARC_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS GLGMG,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '09' THEN NSDM_V_MARC_AGG.STOCK_VKWRT	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS VKGLG,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '10' THEN NSDM_V_MARC_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS BWESB,	
MAX( NSDM_V_MARC_AGG.GJPER_MAX ) AS GJPER,	
'X' AS MCRUE,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '05' THEN NSDM_V_MARC_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_UMLMC,	
SUM(		
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '06' THEN NSDM_V_MARC_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_TRAME ,	
SUM(	
CASE NSDM_V_MARC_AGG.LBBSA	
WHEN '10' THEN NSDM_V_MARC_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_BWESB	
FROM NSDM_V_MARC_AGG NSDM_V_MARC_AGG	
GROUP BY NSDM_V_MARC_AGG.MANDT,	
NSDM_V_MARC_AGG.MATNR,	
NSDM_V_MARC_AGG.WERKS
)

SELECT	
T.MANDT,	
T.MATNR,	
T.WERKS,	
T.PSTAT,	
T.LVORM,	
T.BWTTY,	
T.XCHAR,	
T.MMSTA,	
T.MMSTD,	
T.MAABC,	
T.KZKRI,	
T.EKGRP,	
T.AUSME,	
T.DISPR,	
T.DISMM,	
T.DISPO,	
T.KZDIE,	
T.PLIFZ,	
T.WEBAZ,	
T.PERKZ,	
T.AUSSS,	
T.DISLS,	
T.BESKZ,	
T.SOBSL,	
T.MINBE,	
T.EISBE,	
T.BSTMI,	
T.BSTMA,	
T.BSTFE,	
T.BSTRF,	
T.MABST,	
T.LOSFX,	
T.SBDKZ,	
T.LAGPR,	
T.ALTSL,	
T.KZAUS,	
T.AUSDT,	
T.NFMAT,	
T.KZBED,	
T.MISKZ,	
T.FHORI,	
T.PFREI,	
T.FFREI,	
T.RGEKZ,	
T.FEVOR,	
T.BEARZ,	
T.RUEZT,	
T.TRANZ,	
T.BASMG,	
T.DZEIT,	
T.MAXLZ,	
T.LZEIH,	
T.KZPRO,	
T.GPMKZ,	
T.UEETO,	
T.UEETK,	
T.UNETO,	
T.WZEIT,	
T.ATPKZ,	
T.VZUSL,	
T.HERBL,	
T.INSMK,	
T.SPROZ,	
T.QUAZT,	
T.SSQSS,	
T.MPDAU,	
T.KZPPV,	
T.KZDKZ,	
T.WSTGH,	
T.PRFRQ,	
T.NKMPR,	
CASE	
WHEN  M.UMLMC IS NULL THEN 0	
ELSE M.UMLMC END AS UMLMC,	
T.LADGR,	
T.XCHPF,	
T.USEQU,	
T.LGRAD,	
T.AUFTL,	
T.PLVAR,	
T.OTYPE,	
T.OBJID,	
T.MTVFP,	
T.PERIV,	
T.KZKFK,	
T.VRVEZ,	
T.VBAMG,	
T.VBEAZ,	
T.LIZYK,	
T.BWSCL,	
T.KAUTB,	
T.KORDB,	
CASE	
WHEN  MATERIALTRADECLASSIFICATION.CCNGN IS NULL THEN ''	
ELSE ( RTRIM( SUBSTRING( MATERIALTRADECLASSIFICATION.CCNGN, 1, 17 ) ) ) END
AS STAWN,	
T.HERKL,	
T.HERKR,	
MATERIALTRADEUNIT.BEMEH AS EXPME,	
T.MTVER,	
T.PRCTR,	
CASE	
WHEN  M.TRAME IS NULL THEN 0	
ELSE M.TRAME END AS TRAME,	
T.MRPPP,	
T.SAUFT,	
T.FXHOR,	
T.VRMOD,	
T.VINT1,	
T.VINT2,	
T.VERKZ,	
T.STLAL,	
T.STLAN,	
T.PLNNR,	
T.APLAL,	
T.LOSGR,	
T.SOBSK,	
T.FRTME,	
T.LGPRO,	
T.DISGR,	
T.KAUSF,	
T.QZGTP,	
T.QMATV,	
T.TAKZT,	
T.RWPRO,	
T.COPAM,	
T.ABCIN,	
T.AWSLS,	
T.SERNP,	
T.CUOBJ,	
T.STDPD,	
T.SFEPR,	
T.XMCNG,	
T.QSSYS,	
T.LFRHY,	
T.RDPRF,	
T.VRBMT,	
T.VRBWK,	
T.VRBDT,	
T.VRBFK,	
T.AUTRU,	
T.PREFE,	
T.PRENC,	
T.PRENO,	
T.PREND,	
T.PRENE,	
T.PRENG,	
T.ITARK,	
T.SERVG,	
T.KZKUP,	
T.STRGR,	
T.CUOBV,	
T.LGFSB,	
T.SCHGT,	
T.CCFIX,	
T.EPRIO,	
T.QMATA,	
T.RESVP,	
T.PLNTY,	
T.UOMGR,	
T.UMRSL,	
T.ABFAC,	
T.SFCPF,	
T.SHFLG,	
T.SHZET,	
T.MDACH,	
T.KZECH,	
T.MEGRU,	
T.MFRGR,	
T.PROFIL,	
CASE	
WHEN  M.VKUMC IS NULL THEN 0	
ELSE M.VKUMC END AS VKUMC,	
CASE	
WHEN  M.VKTRW IS NULL THEN 0	
ELSE M.VKTRW END AS VKTRW,	
T.KZAGL,	
T.FVIDK,		
T.FXPRU,	
T.LOGGR,	
T.FPRFM,	
CASE	
WHEN  M.GLGMG IS NULL THEN 0	
ELSE M.GLGMG END AS GLGMG,	
CASE	
WHEN  M.VKGLG IS NULL THEN 0	
ELSE M.VKGLG END AS VKGLG,	
T.INDUS,	
T.MOWNR,	
T.MOGRU,	
T.CASNR,	
T.GPNUM,	
T.STEUC,	
T.FABKZ,	
T.MATGR,	
T.VSPVB,	
T.DPLFS,	
T.DPLPU,	
T.DPLHO,	
T.MINLS,	
T.MAXLS,	
T.FIXLS,	
T.LTINC,	
T.COMPL,	
T.CONVT,	
T.SHPRO,	
T.AHDIS,	
T.DIBER,	
T.KZPSP,	
T.OCMPF,	
T.APOKZ,	
'X' AS MCRUE,	
CASE	
WHEN  ( M.GJPER = '0000000'	
OR M.GJPER IS NULL )  THEN T.LFMON	
ELSE ( RTRIM( SUBSTRING( M.GJPER, 6, 2 ) ) ) END AS LFMON,	
CASE	
WHEN  ( M.GJPER = '0000000'	
OR M.GJPER IS NULL )  THEN T.LFGJA	
ELSE ( RTRIM( SUBSTRING( M.GJPER, 1, 4 ) ) ) END AS LFGJA,	
T.EISLO,	
T.NCOST,	
T.ROTATION_DATE,	
T.UCHKZ,	
T.UCMAT,	
CASE	
WHEN  M.BWESB IS NULL THEN 0	
ELSE M.BWESB END AS BWESB,	
T.SGT_COVS,	
T.SGT_STATC,	
T.SGT_SCOPE,	
'' AS SGT_MRPSI,	
'' AS SGT_PRCM,	
'' AS SGT_CHINT,	
'' AS SGT_STK_PRT,	
T.SGT_DEFSC,	
'' AS SGT_MRP_ATP_STATUS,	
T.SGT_MMSTD,	
T.FSH_MG_ARUN_REQ,	
'' AS FSH_SEAIM,	
T.FSH_VAR_GROUP,	
'' AS FSH_KZECH,	
T.FSH_CALENDAR_GROUP,	
T.ARUN_FIX_BATCH,	
T.PPSKZ,	
T.CONS_PROCG,	
T.GI_PR_TIME,	
T.MULTIPLE_EKGRP,	
T.REF_SCHEMA,	
T.MIN_TROC,	
T.MAX_TROC,	
T.TARGET_STOCK,	
T.NF_FLAG,	
CASE	
WHEN  M._CWM_UMLMC IS NULL THEN 0	
ELSE M._CWM_UMLMC END AS _CWM_UMLMC,	
CASE	
WHEN  M._CWM_TRAME  IS NULL THEN 0	
ELSE M._CWM_TRAME  END AS _CWM_TRAME ,	
CASE	
WHEN  M._CWM_BWESB IS NULL THEN 0	
ELSE M._CWM_BWESB END AS _CWM_BWESB,	
T.SCM_MATLOCID_GUID16,	
T.SCM_MATLOCID_GUID22,	
T.SCM_GRPRT,	
T.SCM_GIPRT,	
T.SCM_SCOST,	
T.SCM_RELDT,	
T.SCM_RRP_TYPE,	
T.SCM_HEUR_ID,	
T.SCM_PACKAGE_ID,	
T.SCM_SSPEN,	
T.SCM_GET_ALERTS,	
T.SCM_RES_NET_NAME,	
T.SCM_CONHAP,	
T.SCM_HUNIT,	
T.SCM_CONHAP_OUT,	
T.SCM_HUNIT_OUT,	
T.SCM_SHELF_LIFE_LOC,	
T.SCM_SHELF_LIFE_DUR,	
T.SCM_MATURITY_DUR,	
T.SCM_SHLF_LFE_REQ_MIN,	
T.SCM_SHLF_LFE_REQ_MAX,	
T.SCM_LSUOM,	
T.SCM_REORD_DUR,	
T.SCM_TARGET_DUR,	
T.SCM_TSTRID,	
T.SCM_STRA1,	
T.SCM_PEG_PAST_ALERT,	
T.SCM_PEG_FUTURE_ALERT,	
T.SCM_PEG_STRATEGY,	
T.SCM_PEG_WO_ALERT_FST,	
T.SCM_FIXPEG_PROD_SET,	
T.SCM_WHATBOM,	
T.DUMMY_PLNT_INCL_EEW_PS,	
T.SCM_RRP_SEL_GROUP,	
T.SCM_INTSRC_PROF,	
T.SCM_PRIO,	
T.SCM_MIN_PASS_AMOUNT,	
T.SCM_PROFID,	
T.SCM_GES_MNG_USE,	
T.SCM_GES_BST_USE,	
T.ESPPFLG,	
T.SCM_THRUPUT_TIME,	
T.SCM_TPOP,	
T.SCM_SAFTY_V,	
T.SCM_PPSAFTYSTK,	
T.SCM_PPSAFTYSTK_V,	
T.SCM_REPSAFTY,	
T.SCM_REPSAFTY_V,	
T.SCM_REORD_V,	
T.SCM_MAXSTOCK_V,	
T.SCM_SCOST_PRCNT,	
T.SCM_PROC_COST,	
T.SCM_NDCOSTWA,	
T.SCM_NDCOSTWE,	
T.EXCISE_TAX_RLVNCE,	
T.SCM_CONINP,	
T.CONF_GMSYNC,	
T.SCM_IUNIT,	
T.SCM_SFT_LOCK,	
T.SFTY_STK_METH,	
T.TEMP_CTRL_MIN,	
T.TEMP_CTRL_MAX,	
T.TEMP_UOM,	
T.JITPRODNCONFPROFILE,	
T._SAPMP_TOLPRPL,	
T._SAPMP_TOLPRMI,	
T._STTPEC_SERVALID,	
T._VSO_R_PKGRP,	
T._VSO_R_LANE_NUM,	
T._VSO_R_PAL_VEND,	
T._VSO_R_FORK_DIR,	
T.IUID_RELEVANT,	
T.IUID_TYPE,	
T.UID_IEA,	
T.DPCBT	
FROM {{ source('raw_tables', 'marc') }} T	
LEFT OUTER JOIN {{ source('raw_tables', 't001w') }} PLANT	
ON ( PLANT.MANDT = T.MANDT	
AND PLANT.WERKS = T.WERKS	
AND T.MANDT = PLANT.MANDT )
LEFT OUTER JOIN {{ source('raw_tables', '_sapsll_tunos') }} NUMBERSCEMEUSAGE	
ON ( PLANT.MANDT = NUMBERSCEMEUSAGE.MANDT	
AND PLANT.LAND1 = NUMBERSCEMEUSAGE.LAND1	
AND NUMBERSCEMEUSAGE.CTSTY = '01'	
AND T.MANDT = NUMBERSCEMEUSAGE.MANDT )	
LEFT OUTER JOIN	{{ source('raw_tables', '_sapsll_maritc') }} MATERIALTRADECLASSIFICATION	
ON ( MATERIALTRADECLASSIFICATION.MANDT = T.MANDT	
AND MATERIALTRADECLASSIFICATION.MATNR = T.MATNR	
AND MATERIALTRADECLASSIFICATION.STCTS = NUMBERSCEMEUSAGE.STCTS	
AND MATERIALTRADECLASSIFICATION.DATAB <= to_char(current_date(), 'yyyyMMdd')
AND MATERIALTRADECLASSIFICATION.DATBI >= to_char(current_date(), 'yyyyMMdd')
AND T.MANDT = MATERIALTRADECLASSIFICATION.MANDT )
LEFT OUTER JOIN	{{ source('raw_tables', '_sapsll_nosca') }} NUMBERSCHEMECONTENT	
ON ( NUMBERSCHEMECONTENT.STCTS = NUMBERSCEMEUSAGE.STCTS	
AND NUMBERSCHEMECONTENT.DATAB <= to_char(current_date(), 'yyyyMMdd')	
AND NUMBERSCHEMECONTENT.DATBI >= to_char(current_date(), 'yyyyMMdd')	
AND T.MANDT = NUMBERSCHEMECONTENT.MANDT )
LEFT OUTER JOIN {{ source('raw_tables', '_sapsll_clsnr') }} MATERIALTRADEUNIT	
ON ( MATERIALTRADEUNIT.NOSCT = NUMBERSCHEMECONTENT.NOSCT	
AND MATERIALTRADEUNIT.CCNGN = MATERIALTRADECLASSIFICATION.CCNGN	
AND MATERIALTRADEUNIT.DATAB <= to_char(current_date(), 'yyyyMMdd')	
AND MATERIALTRADEUNIT.DATBI >= to_char(current_date(), 'yyyyMMdd')	
AND T.MANDT = MATERIALTRADEUNIT.MANDT )	
LEFT OUTER JOIN NSDM_V_MARC_DIFF M	
ON ( T.MANDT = M.MANDT	
AND T.MATNR = M.MATNR	
AND T.WERKS = M.WERKS	
AND T.MANDT = M.MANDT )

