with NSDM_V_MCHB_AGG AS	(
SELECT	
MATDOC_EXTRACT.MANDT,	
MATDOC_EXTRACT.MATBF AS MATNR,	
MATDOC_EXTRACT.WERKS,	
MATDOC_EXTRACT.LGORT_SID AS LGORT,	
MATDOC_EXTRACT.CHARG_SID AS CHARG,	
MATDOC_EXTRACT.LBBSA_SID AS LBBSA,	
SUM( MATDOC_EXTRACT.STOCK_QTY_L1 ) AS STOCK_QTY,	
SUM( MATDOC_EXTRACT._CWM_STOCK_QTY_L1 ) AS _CWM_STOCK_QTY,	
MAX( MATDOC_EXTRACT.GJPER_CURR_PER ) AS GJPER_MAX	
FROM {{ source('raw_tables', 'matdoc_extract') }} MATDOC_EXTRACT	
WHERE	
( NOT ( MATDOC_EXTRACT.CHARG_SID = '' )	
AND ( MATDOC_EXTRACT.SOBKZ = ''	
AND ( MATDOC_EXTRACT.LBBSA_SID = '01'	
OR MATDOC_EXTRACT.LBBSA_SID = '02'	
OR MATDOC_EXTRACT.LBBSA_SID = '03'	
OR MATDOC_EXTRACT.LBBSA_SID = '04'	
OR MATDOC_EXTRACT.LBBSA_SID = '07'	
OR MATDOC_EXTRACT.LBBSA_SID = '08' ) ) )	
GROUP BY MATDOC_EXTRACT.MANDT,	
MATDOC_EXTRACT.MATBF,	
MATDOC_EXTRACT.WERKS,	
MATDOC_EXTRACT.LGORT_SID,	
MATDOC_EXTRACT.CHARG_SID,	
MATDOC_EXTRACT.LBBSA_SID
)
, 

NSDM_V_MCHB_DIFF AS	(
SELECT	
NSDM_V_MCHB_AGG.MANDT,	
NSDM_V_MCHB_AGG.MATNR,	
NSDM_V_MCHB_AGG.WERKS,	
NSDM_V_MCHB_AGG.LGORT,	
NSDM_V_MCHB_AGG.CHARG,	
MAX( NSDM_V_MCHB_AGG.GJPER_MAX ) AS GJPER,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '01' THEN NSDM_V_MCHB_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS CLABS,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '04' THEN NSDM_V_MCHB_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS CUMLM,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '02' THEN NSDM_V_MCHB_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS CINSM,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '08' THEN NSDM_V_MCHB_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS CEINM,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '07' THEN NSDM_V_MCHB_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS CSPEM,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '03' THEN NSDM_V_MCHB_AGG.STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS CRETM,	
CAST( 0 AS DECIMAL(13,3) ) AS CVMLA,	
CAST( 0 AS DECIMAL(13,3) ) AS CVMUM,	
CAST( 0 AS DECIMAL(13,3) ) AS CVMIN,	
CAST( 0 AS DECIMAL(13,3) ) AS CVMEI,	
CAST( 0 AS DECIMAL(13,3) ) AS CVMSP,	
CAST( 0 AS DECIMAL(13,3) ) AS CVMRE,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '01' THEN NSDM_V_MCHB_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_CLABS,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '04' THEN NSDM_V_MCHB_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_CUMLM,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '02' THEN NSDM_V_MCHB_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_CINSM,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '08' THEN NSDM_V_MCHB_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_CEINM,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '07' THEN NSDM_V_MCHB_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_CSPEM,	
SUM(	
CASE NSDM_V_MCHB_AGG.LBBSA	
WHEN '03' THEN NSDM_V_MCHB_AGG._CWM_STOCK_QTY	
ELSE CAST( 0 AS DECIMAL(13,0)) END ) AS _CWM_CRETM,	
CAST( 0 AS DECIMAL(13,3) ) AS _CWM_CVMLA,	
CAST( 0 AS DECIMAL(13,3) ) AS _CWM_CVMUM,	
CAST( 0 AS DECIMAL(13,3) ) AS _CWM_CVMIN,	
CAST( 0 AS DECIMAL(13,3) ) AS _CWM_CVMEI,	
CAST( 0 AS DECIMAL(13,3) ) AS _CWM_CVMSP,	
CAST( 0 AS DECIMAL(13,3) ) AS _CWM_CVMRE,	
'X' AS CHRUE	
FROM NSDM_V_MCHB_AGG NSDM_V_MCHB_AGG	
GROUP BY NSDM_V_MCHB_AGG.MANDT,	
NSDM_V_MCHB_AGG.MATNR,	
NSDM_V_MCHB_AGG.WERKS,	
NSDM_V_MCHB_AGG.LGORT,	
NSDM_V_MCHB_AGG.CHARG
)

SELECT	
T.MANDT,	
T.MATNR,	
T.WERKS,	
T.LGORT,	
T.CHARG,	
T.LVORM,	
T.ERSDA,	
T.ERNAM,	
T.LAEDA,	
T.AENAM,	
CASE	
WHEN  ( M.GJPER = '0000000'	
OR M.GJPER IS NULL )  THEN T.LFGJA	
ELSE ( RTRIM( SUBSTRING( M.GJPER, 1, 4 ) ) ) END AS LFGJA,	
CASE	
WHEN  ( M.GJPER = '0000000'	
OR M.GJPER IS NULL )  THEN T.LFMON	
ELSE ( RTRIM( SUBSTRING( M.GJPER, 6, 2 ) ) ) END AS LFMON,
T.SPERC,	
CASE	
WHEN  M.CLABS IS NULL THEN 0	
ELSE M.CLABS END AS CLABS,	
CASE	
WHEN  M.CUMLM IS NULL THEN 0	
ELSE M.CUMLM END AS CUMLM,	
CASE	
WHEN  M.CINSM IS NULL THEN 0	
ELSE M.CINSM END AS CINSM,	
CASE	
WHEN  M.CEINM IS NULL THEN 0	
ELSE M.CEINM END AS CEINM,	
CASE	
WHEN  M.CSPEM IS NULL THEN 0	
ELSE M.CSPEM END AS CSPEM,	
CASE	
WHEN  M.CRETM IS NULL THEN 0	
ELSE M.CRETM END AS CRETM,	
CASE	
WHEN  M.CVMLA IS NULL THEN 0	
ELSE M.CVMLA END AS CVMLA,	
CASE	
WHEN  M.CVMUM IS NULL THEN 0	
ELSE M.CVMUM END AS CVMUM,	
CASE	
WHEN  M.CVMIN IS NULL THEN 0	
ELSE M.CVMIN END AS CVMIN,	
CASE	
WHEN  M.CVMEI IS NULL THEN 0	
ELSE M.CVMEI END AS CVMEI,	
CASE	
WHEN  M.CVMSP IS NULL THEN 0	
ELSE M.CVMSP END AS CVMSP,	
CASE	
WHEN  M.CVMRE IS NULL THEN 0	
ELSE M.CVMRE END AS CVMRE,	
T.KZICL,	
T.KZICQ,	
T.KZICE,	
T.KZICS,	
T.KZVCL,	
T.KZVCQ,	
T.KZVCE,	
T.KZVCS,	
T.HERKL,	
T.CHDLL,	
T.CHJIN,	
'X' AS CHRUE,	
T.SGT_SCAT,	
'' AS FSH_SEASON_YEAR,	
'' AS FSH_SEASON,	
'' AS FSH_COLLECTION,	
'' AS FSH_THEME,	
T.FSH_SALLOC_QTY,	
CASE	
WHEN  M._CWM_CLABS IS NULL THEN 0	
ELSE M._CWM_CLABS END AS _CWM_CLABS,	
CASE	
WHEN  M._CWM_CINSM IS NULL THEN 0	
ELSE M._CWM_CINSM END AS _CWM_CINSM,	
CASE	
WHEN  M._CWM_CEINM IS NULL THEN 0	
ELSE M._CWM_CEINM END AS _CWM_CEINM,	
CASE	
WHEN  M._CWM_CSPEM IS NULL THEN 0	
ELSE M._CWM_CSPEM END AS _CWM_CSPEM,	
CASE	
WHEN  M._CWM_CRETM IS NULL THEN 0	
ELSE M._CWM_CRETM END AS _CWM_CRETM,	
CASE	
WHEN  M._CWM_CUMLM IS NULL THEN 0	
ELSE M._CWM_CUMLM END AS _CWM_CUMLM,	
CASE	
WHEN  M._CWM_CVMLA IS NULL THEN 0	
ELSE M._CWM_CVMLA END AS _CWM_CVMLA,	
CASE	
WHEN  M._CWM_CVMIN IS NULL THEN 0	
ELSE M._CWM_CVMIN END AS _CWM_CVMIN,	
CASE	
WHEN  M._CWM_CVMEI IS NULL THEN 0	
ELSE M._CWM_CVMEI END AS _CWM_CVMEI,	
CASE	
WHEN  M._CWM_CVMSP IS NULL THEN 0	
ELSE M._CWM_CVMSP END AS _CWM_CVMSP,	
CASE	
WHEN  M._CWM_CVMRE IS NULL THEN 0	
ELSE M._CWM_CVMRE END AS _CWM_CVMRE,	
CASE	
WHEN  M._CWM_CVMUM IS NULL THEN 0	
ELSE M._CWM_CVMUM END AS _CWM_CVMUM	
FROM {{ source('raw_tables', 'mchb') }} T	
LEFT OUTER JOIN NSDM_V_MCHB_DIFF M	
ON ( T.MANDT = M.MANDT	
AND T.MATNR = M.MATNR	
AND T.WERKS = M.WERKS	
AND T.LGORT = M.LGORT	
AND T.CHARG = M.CHARG	
AND T.MANDT = M.MANDT )
